'use strict';
(()=>{
const data=window.RAMEN_CATALOG;if(!data){document.getElementById('event-list').innerHTML='<div class="notice">データを読み込めませんでした。下の公式タイムテーブルをご利用ください。</div>';return;}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).replace(/[‐‑–—]/g,'-').replace(/\s+/g,' ').trim(),venues=new Map(data.venues.map(v=>[v.id,v])),events=data.events;
const rootURL='https://mobilitydlab.com/GarrawayFapp.github.io/ramen-tech-2026/',KEY='garrawayf-ramen-city-2026-favorites-v2';
let saved=new Set(),storageOK=true;try{const raw=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('garrawayf-ramen-tech-2026-favorites-v1')||'[]');if(Array.isArray(raw))saved=new Set(raw.filter(x=>events.some(e=>e.id===x)));}catch{storageOK=false;}
const params=new URLSearchParams(location.search),validDays=['all','any','pre','after','1','2','3','4','5','6','7','8','9','10','11','12','13','14'];
const PAGE_SIZE=18;
const validTime=t=>/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(t||'')?t:'';
const defaults={day:'all',venue:'all',query:'',category:'all',period:'all',area:'all',fee:'all',from:'',until:'',known:false,sessions:true,saved:false,order:'time',layout:'list',limit:PAGE_SIZE};
function readState(){const p=new URLSearchParams(location.search);return {...defaults,day:validDays.includes(p.get('date'))?p.get('date'):'all',venue:venues.has(p.get('venue'))?p.get('venue'):'all',query:(p.get('q')||'').slice(0,160),category:data.events.some(e=>e.category===p.get('theme'))?p.get('theme'):'all',period:['morning','afternoon','evening','unknown'].includes(p.get('period'))?p.get('period'):'all',area:data.venues.some(v=>v.area===p.get('area'))?p.get('area'):'all',fee:['free','no-registration'].includes(p.get('fee'))?p.get('fee'):'all',from:validTime(p.get('from')),until:validTime(p.get('until')),known:p.get('known')==='1',sessions:p.get('sessions')!=='0',order:['time','venue','relevance'].includes(p.get('order'))?p.get('order'):'time',layout:p.get('view')==='cards'?'cards':'list'};}
let state=readState();
let venueState={role:'all',query:'',limit:12},detail=null,detailDay=null,toastTimer;
const colors={'AI・技術':'#1892F5','交流':'#EF7BD7','ピッチ':'#FFE248','ビジネス・共創':'#64D84A','アート・デザイン':'#FF5A45','教育':'#1892F5','体験・ウェルネス':'#64D84A'};
const weekday=iso=>['日','月','火','水','木','金','土'][new Date(iso+'T12:00:00+09:00').getUTCDay()];
const dateName=iso=>`${Number(iso.slice(5,7))}/${Number(iso.slice(8,10))}（${weekday(iso)}）`;
const rangeName=e=>e.dates.length===1?dateName(e.dates[0]):`${dateName(e.dates[0])}〜${dateName(e.dates.at(-1))}`;
const getTime=(e,day)=>e.slots?.[day]||[e.start,e.end];
function inScope(day,st=state){if(st.day==='any')return true;if(st.day==='all')return day>='2026-10-07'&&day<='2026-10-11';if(st.day==='pre')return day>='2026-09-30'&&day<'2026-10-07';if(st.day==='after')return day>'2026-10-11';return day==='2026-10-'+st.day.padStart(2,'0');}
function visibleDay(e){return e.dates.find(day=>inScope(day))||e.dates[0];}
const venueAliases={garraway:'ギャラウェイ ぎゃらうぇい GarrawayF ギャラウェー',one6:'ワンビル ONE FUKUOKA ワン福岡',one7:'ワンビル ONE FUKUOKA ワン福岡',daimyo:'大名カンファレンス Daimyo Conference',cic:'シーアイシー CIC',fgn:'FGN 福岡グロースネクスト グロースネクスト'};
const synonyms=[['ai','人工知能','生成ai'],['交流','meetup','ミートアップ','networking','ネットワーキング'],['pitch','ピッチ'],['startup','スタートアップ','起業'],['art','アート'],['design','デザイン'],['education','教育'],['nomad','ノマド'],['wellness','ウェルネス'],['free','無料']].map(a=>a.map(normalize));
const queryTerms=q=>(String(q).match(/"[^"]+"|\S+/g)||[]).map(t=>normalize(t.replace(/^"|"$/g,''))).filter(Boolean);
function contains(text,term){if(/^[a-z]{1,2}$/.test(term))return new RegExp('(^|[^a-z0-9])'+term+'(?=$|[^a-z0-9])','i').test(text);return text.includes(term)||text.replace(/[\s._-]/g,'').includes(term.replace(/[\s._-]/g,''));}
function termMatch(text,term){const group=synonyms.find(a=>a.includes(term));return (group||[term]).some(t=>contains(text,t));}
const searchIndex=new Map(events.map(e=>{const v=venues.get(e.venue);return [e.id,normalize([e.title,e.parentTitle,e.room,v.name,v.area,venueAliases[e.venue]||'',e.category,...(e.tags||[]),e.fee,...(e.notes||[])].join(' '))];}));
function matches(e,st){const v=venues.get(e.venue);return (st.venue==='all'||e.venue===st.venue)&&(st.area==='all'||v.area===st.area)&&(st.category==='all'||e.category===st.category)&&(st.sessions||e.kind==='event')&&(!st.saved||saved.has(e.id))&&(st.fee==='all'||(st.fee==='free'?e.fee.includes('無料'):e.fee.includes('無料')&&e.fee.includes('予約不要')))&&queryTerms(st.query).every(t=>termMatch(searchIndex.get(e.id),t));}
function timeMatch(e,day,st){const [start,end]=getTime(e,day),known=!!start&&!!end&&!e.calendarBlocked;if(st.from&&st.until&&st.from>=st.until)return false;if(st.known&&!known)return false;if(st.period==='unknown'&&known)return false;if(st.period!=='all'&&st.period!=='unknown'){if(!known)return false;const [low,high]={morning:['00:00','12:00'],afternoon:['12:00','18:00'],evening:['18:00','24:00']}[st.period];if(!(start<high&&end>low))return false;}if((st.from||st.until)&&!known)return false;return (!st.from||start>=st.from)&&(!st.until||end<=st.until);}
function searchScore(e,st){return queryTerms(st.query).reduce((n,t)=>n+(contains(normalize(e.title),t)?8:0)+(termMatch(normalize(e.title+' '+e.category),t)?3:0),0);}
function highlight(value){const terms=queryTerms(state.query).filter(t=>t.length>1);if(!terms.length)return esc(value);const pat=terms.map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');return String(value||'').split(new RegExp('('+pat+')','gi')).map((part,i)=>i%2?'<mark>'+esc(part)+'</mark>':esc(part)).join('');}
function filtered(patch={}){const st={...state,...patch};return events.filter(e=>matches(e,st)).flatMap(e=>e.dates.filter(day=>inScope(day,st)&&timeMatch(e,day,st)).map(day=>({e,day}))).sort((a,b)=>{if(st.order==='relevance'&&st.query){const r=searchScore(b.e,st)-searchScore(a.e,st);if(r)return r;}if(st.order==='venue'){const c=venues.get(a.e.venue).name.localeCompare(venues.get(b.e.venue).name,'ja');if(c)return c;}return a.day.localeCompare(b.day)||(getTime(a.e,a.day)[0]||'99:99').localeCompare(getTime(b.e,b.day)[0]||'99:99')||a.e.title.localeCompare(b.e.title,'ja');});}
function stateURL(){const u=new URL(rootURL);u.searchParams.set('date',state.day);for(const [key,param] of Object.entries({venue:'venue',query:'q',category:'theme',period:'period',area:'area',fee:'fee',from:'from',until:'until',order:'order',layout:'view'})){if(state[key]&&state[key]!==defaults[key])u.searchParams.set(param,state[key]);}if(state.known)u.searchParams.set('known','1');if(!state.sessions)u.searchParams.set('sessions','0');u.hash='schedule';return u;}
function syncURL(){try{if(!['https:','http:'].includes(location.protocol))return;const u=stateURL();u.pathname=location.pathname;u.hash=location.hash;const eventId=new URLSearchParams(location.search).get('event');if(eventId){u.searchParams.set('event',eventId);const on=new URLSearchParams(location.search).get('on');if(on)u.searchParams.set('on',on);}history.replaceState(null,'',u.pathname+u.search+u.hash);}catch{}}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3700);}
function statusLabel(e){if(e.status==='cancelled')return '<span class="label warn">中止表記</span>';if(e.status==='check')return '<span class="label warn">要確認</span>';if(e.status==='soldout')return '<span class="label soldout">完売表記</span>';if(e.origin==='主催者予定')return '<span class="label planned">主催者予定</span>';return '';}
function card(e,day){const [start,end]=getTime(e,day),v=venues.get(e.venue);return `<article class="event-card" style="--accent:${colors[e.category]||'#1892F5'}"><div class="card-strip"></div><div class="card-content"><div class="event-clock"><p class="event-date">${esc(dateName(day))}</p><p class="event-time ${start?'':'pending'}">${start?esc(start)+(end?'<small>—</small>'+esc(end):'<small>〜</small>'):'時刻未公表'}</p>${e.dates.length>1?'<p class="date-range"><span class="date-label">複数日開催</span><br>'+esc(rangeName(e))+'<br>時刻は '+esc(dateName(day))+' の予定</p>':''}</div><div class="event-summary"><button class="event-title" data-detail="${esc(e.id)}" data-on="${day}">${highlight(e.title)}</button><p class="place-name">${highlight(v.name)}</p><p class="room-name">${highlight(v.area)}${e.room?' / '+highlight(e.room):''}</p>${e.parentTitle?'<p class="card-parent">イベント：'+highlight(e.parentTitle)+'</p>':''}<div class="card-labels"><span class="label">${highlight(e.category)}</span><span class="label">${e.kind==='session'?'個別セッション':esc(e.origin)}</span>${statusLabel(e)}</div><p class="fee-line">参加条件：<strong>${esc(e.fee)}</strong></p></div><button class="save-button" data-save="${esc(e.id)}" data-on="${day}" aria-label="${esc(e.title)}を${saved.has(e.id)?'マイ予定から削除':'マイ予定に保存'}" aria-pressed="${saved.has(e.id)}">${saved.has(e.id)?'♥':'♡'}</button><div class="card-bottom"><button class="more-link" data-detail="${esc(e.id)}" data-on="${day}">詳細・予定に追加 ↗</button>${e.url?'<a href="'+esc(e.url)+'" target="_blank" rel="noopener noreferrer">主催者案内 ↗</a>':'<span class="label">Garraway F企画</span>'}</div></div></article>`;}
function scopeName(){const name=state.day==='any'?'全期間':state.day==='all'?'10/7–11 本会期':state.day==='pre'?'9/30–10/6 前日程':state.day==='after'?'10/12–14 後日程':dateName('2026-10-'+state.day.padStart(2,'0'));return (state.saved?'マイ予定 / ':'')+name;}
function overlapCount(){const selected=events.filter(e=>saved.has(e.id));let count=0;for(let i=0;i<selected.length;i++)for(let j=i+1;j<selected.length;j++){const a=selected[i],b=selected[j];if(a.parent===b.id||b.parent===a.id)continue;for(const day of a.dates.filter(d=>b.dates.includes(d))){const [as,ae]=getTime(a,day),[bs,be]=getTime(b,day);if(as&&ae&&bs&&be&&as<be&&bs<ae)count++;}}return count;}

function renderActive(){const labels=[];if(state.query)labels.push(['query','検索：'+state.query]);if(state.day!=='any')labels.push(['day',scopeName().replace('マイ予定 / ','')]);if(state.venue!=='all')labels.push(['venue',venues.get(state.venue).name]);if(state.category!=='all')labels.push(['category',state.category]);if(state.area!=='all')labels.push(['area',state.area]);if(state.period!=='all')labels.push(['period',{morning:'朝・午前',afternoon:'午後',evening:'夜',unknown:'時刻未公表・要確認'}[state.period]]);if(state.fee!=='all')labels.push(['fee',state.fee==='free'?'無料と明記':'無料・予約不要']);if(state.from)labels.push(['from',state.from+'以降に開始']);if(state.until)labels.push(['until',state.until+'までに終了']);if(state.known)labels.push(['known','時刻確認済みのみ']);if(!state.sessions)labels.push(['sessions','イベントのみ']);if(state.saved)labels.push(['saved','マイ予定']);$('#active-filters').innerHTML=labels.map(([key,label])=>'<button data-clear="'+key+'" aria-label="'+esc(label)+'の条件を解除">'+esc(label)+' ×</button>').join('');}
function render(){const found=filtered(),unique=new Set(found.map(x=>x.e.id)).size;
$$('[data-day]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.day===state.day)));
for(const [selector,key] of Object.entries({'#venue-select':'venue','#category-select':'category','#time-select':'period','#area-select':'area','#fee-select':'fee','#time-from':'from','#time-to':'until','#sort-select':'order'})){$(selector).value=state[key];}
$('#include-sessions').checked=state.sessions;$('#known-only').checked=state.known;$('#favorite-filter').setAttribute('aria-pressed',String(state.saved));$('#saved-count').textContent=saved.size;$('#mobile-saved-count').textContent=saved.size;
$('#clear-query').hidden=!state.query;$('#time-error').hidden=!(state.from&&state.until&&state.from>=state.until);
$$('[data-layout]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===state.layout)));
$('#event-list').className='event-list layout-'+state.layout;
$('#result-label').textContent=`${scopeName()} / ${unique}件・${found.length}日程`;
$('#display-count').textContent=`${Math.min(state.limit,found.length)} / ${found.length}日程を表示（複数日開催は日別に表示）`;
const notice=$('#special-notice');let message='';if(state.saved&&overlapCount())message=`マイ予定に時間帯の重複が${overlapCount()}件あります。参加日ごとの移動・時間の調整は「移動込みの予定表」で確認できます。`;else if(state.venue==='garraway'&&['7','all','any'].includes(state.day))message='10/7午後はSHE SAILS（14:00–16:30）とWELCOME KYUSHU!（14:00–17:00）が重複しています。館内の利用区画・同時開催条件は要確認です。';else if(state.day==='pre')message='RAMEN TECH本会期は10/7〜11です。ここには前日程の関連イベント・滞在プログラムを掲載しています。';else if(state.day==='after')message='10/12〜14は本会期の後日程です。期間をまたぐ滞在プログラム等を区別しています。';notice.hidden=!message;notice.textContent=message;
const shown=found.slice(0,state.limit);if(!shown.length){const wider=state.day==='any'?0:new Set(filtered({day:'any'}).map(x=>x.e.id)).size;$('#event-list').innerHTML=`<div class="empty"><h3>${state.saved&&!saved.size?'マイ予定は、ここから。':'この条件の掲載情報はありません。'}</h3><p>${state.saved&&!saved.size?'♡を押すと、このブラウザに予定を保存できます。':'選択中の日付・会場・時間帯を変えてみてください。<br>未公表の予定は、検索結果に含まれません。'}</p><div class="empty-actions">${wider?'<button class="button lemon" data-act="widen">全期間で探す（'+wider+'件） ↗</button>':''}<button class="button white" data-act="reset">すべての条件を解除</button></div></div>`;}else{let last='',html='';for(const item of shown){const group=state.order==='venue'?venues.get(item.e.venue).name:state.order==='relevance'&&state.query?'検索との関連度順':dateName(item.day);if(group!==last){if(last)html+='</div>';html+='<h3 class="group-title">'+esc(group)+'</h3><div class="cards">';last=group;}html+=card(item.e,item.day);}$('#event-list').innerHTML=html+'</div>';}
$('#load-more').hidden=found.length<=state.limit;$('#show-all').hidden=found.length<=state.limit;$('#load-more').textContent=`次の${Math.min(PAGE_SIZE,Math.max(0,found.length-state.limit))}日程を見る ↓`;$('#download-saved').hidden=!state.saved||!saved.size;renderActive();syncURL();document.dispatchEvent(new CustomEvent("ramen:render"));}
function change(patch){Object.assign(state,patch,{limit:PAGE_SIZE});if($('#search').value!==state.query)$('#search').value=state.query;render();}
function reset(){change({...defaults,day:'any',layout:state.layout});$('#search').value='';}
function goVenue(id){change({...defaults,venue:id,day:'any',layout:state.layout});$('#search').value='';$('#schedule').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
function save(id,day){const add=!saved.has(id);add?saved.add(id):saved.delete(id);try{localStorage.setItem(KEY,JSON.stringify([...saved]));storageOK=true;}catch{storageOK=false;}render();if(detail&&$('#detail-dialog').open)drawDetail();const btn=$$('[data-save]').find(b=>b.dataset.save===id);if(btn&&!$('#detail-dialog').open)btn.focus({preventScroll:true});document.dispatchEvent(new CustomEvent('ramen:saved',{detail:{id,day:day||detailDay,add}}));toast((add?'マイ予定に保存しました':'マイ予定から削除しました')+(storageOK?'':'（この画面を閉じるまで有効）'));}
function venueRender(){const terms=queryTerms(venueState.query);const rows=data.venues.filter(v=>!['tbd','private','city','kyushu-venues'].includes(v.id)&&(venueState.role==='all'||v.roles.includes(venueState.role))&&terms.every(t=>termMatch(normalize(v.name+' '+v.area+' '+(venueAliases[v.id]||'')),t))).sort((a,b)=>b.eventCount-a.eventCount||a.name.localeCompare(b.name,'ja'));$('#venue-list').innerHTML=rows.slice(0,venueState.limit).map((v,i)=>`<article class="venue-card"><div class="venue-num"><span>${String(i+1).padStart(2,'0')} / ${esc(v.area)}</span><span>${v.eventCount?v.eventCount+'掲載枠':'イベント未確認'}</span></div><h3>${esc(v.name)}</h3><div class="venue-roles">${v.roles.map(r=>'<span class="'+(r==='コワーキング'?'cowork':'')+'">'+esc(r)+'</span>').join('')}</div>${v.id==='garraway'?'<p>今泉1-19-22 西鉄天神CLASS 3F。ラウンジ開放時間・週末の扱いは確認中。</p>':''}<div class="venue-links"><button data-venue="${esc(v.id)}">${v.eventCount?'この会場の予定 ↗':'掲載状況を確認 ↗'}</button><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(v.name+' 福岡')}" target="_blank" rel="noopener noreferrer">地図 ↗</a>${v.website?'<a href="'+esc(v.website)+'" target="_blank" rel="noopener noreferrer">施設公式 ↗</a>':''}</div></article>`).join('')||'<p class="venue-help">該当する施設はありません。</p>';$('#venue-result').textContent=rows.length+'施設・会場 / '+Math.min(rows.length,venueState.limit)+'件を表示';$('#more-venues').hidden=rows.length<=venueState.limit;$('#more-venues').textContent=`施設をすべて表示（残り${Math.max(0,rows.length-venueState.limit)}件） ↓`;$$('[data-role]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.role===venueState.role)));}
function canCalendar(e,day){const [s,t]=getTime(e,day);return !!validTime(s)&&!!validTime(t)&&t>s&&!e.calendarBlocked;}
function stamp(day,time){return new Date(day+'T'+time+':00+09:00').toISOString().replace(/[-:]/g,'').replace('.000','');}
function eventDescription(e){return [e.fee,...e.notes,'予定の保存であり、参加予約ではありません。','個別確認日：'+(e.checkedAt||data.meta.checkedAt),'出典：'+(e.url||e.source),rootURL+'?event='+encodeURIComponent(e.id)].join('\n');}
function googleURL(e,day){if(!canCalendar(e,day))return '';const [s,t]=getTime(e,day);return 'https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:e.title,dates:stamp(day,s)+'/'+stamp(day,t),ctz:'Asia/Tokyo',location:venues.get(e.venue).name+(e.room?' / '+e.room:''),details:eventDescription(e)}).toString();}
function openDetail(id,day){detail=events.find(e=>e.id===id);if(!detail)return;detailDay=day&&detail.dates.includes(day)?day:visibleDay(detail);drawDetail();if(!$('#detail-dialog').open)$('#detail-dialog').showModal();}
function drawDetail(){const e=detail,day=detailDay,[start,end]=getTime(e,day),v=venues.get(e.venue),url=googleURL(e,day),can=!!url;$('#detail-body').innerHTML=`<div class="card-labels"><span class="label">${esc(e.origin)}</span>${statusLabel(e)}</div><h2 id="detail-title">${esc(e.title)}</h2><p class="detail-time">${start?esc(start)+(end?' — '+esc(end):'〜'):'時刻未公表'}</p><p class="detail-date">${esc(dateName(day))} / 日本時間</p>${e.dates.length>1?'<label class="sr-only" for="detail-day">日付を選んでカレンダーへ追加</label><select id="detail-day" class="detail-day">'+e.dates.map(d=>'<option value="'+d+'" '+(d===day?'selected':'')+'>'+dateName(d)+(getTime(e,d)[0]?' / '+getTime(e,d).join('–'):' / 時刻未公表')+'</option>').join('')+'</select>':''}<p class="detail-venue">${esc(v.name)}</p>${e.room?'<p class="detail-meta">'+esc(e.room)+'</p>':''}<p class="detail-meta">参加条件：${esc(e.fee)}${e.parentTitle?'<br>親イベント：'+esc(e.parentTitle):''}</p><div class="detail-notes">${e.notes.map(n=>'<p>'+esc(n)+'</p>').join('')}${!can?'<p>この日付は時刻未公表、または時刻に不一致があります。誤った予定を保存しないよう、カレンダー追加を停止しています。</p>':''}</div><button class="button detail-save" data-save="${esc(e.id)}" data-on="${day}" aria-pressed="${saved.has(e.id)}">${saved.has(e.id)?'♥ マイ予定に保存済み':'♡ マイ予定に保存する'}</button><div class="detail-actions">${e.url?'<a class="button black wide" href="'+esc(e.url)+'" target="_blank" rel="noopener noreferrer">主催者の詳細・参加案内を開く ↗</a>':''}${can?'<a class="button white" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">Googleカレンダー ＋</a>':'<button class="button white" disabled>Googleカレンダー ＋</button>'}<button class="button white" data-act="ics-one" ${can?'':'disabled'}>Apple・Outlook（.ics）</button>${!['tbd','private','city'].includes(e.venue)?'<a class="button white wide" href="https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(v.name+' 福岡')+'" target="_blank" rel="noopener noreferrer">会場を地図で確認 ↗</a>':''}</div><button class="text-button" data-act="share-event">このイベントだけを共有 ↗</button><p class="privacy-note">カレンダーへの追加は予約ではありません。保存後の開催情報の変更は自動反映されません。</p><div class="detail-source">情報確認：${esc(e.checkedAt||data.meta.checkedAt)}${e.autoCheckedAt?'<br>登録・時間割の自動確認：'+esc(e.autoCheckedAt.replace('T',' ')):''}<br>出典：${String(e.source).startsWith('https://')?'<a href="'+esc(e.source)+'" target="_blank" rel="noopener noreferrer">'+esc(e.origin)+'の掲載元 ↗</a>':esc(e.source)}${e.alsoSources?.length?' / <a href="https://ramentech2026.aishain.com/" target="_blank" rel="noopener noreferrer">公式時間割とも照合 ↗</a>':''}</div>`;}
function escapeICS(s){return String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');}
function foldICS(line){let result='',chunk='',bytes=0;const enc=new TextEncoder();for(const c of line){const len=enc.encode(c).length;if(bytes+len>73){result+=chunk+'\r\n';chunk=' ';bytes=1;}chunk+=c;bytes+=len;}return result+chunk;}
function exportICS(entries){const valid=entries.filter(x=>canCalendar(x.e,x.day));if(!valid.length){toast('カレンダーに保存できる時刻情報がありません。主催者案内をご確認ください。');return;}const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Garraway F//RAMEN CITY GUIDE 2026//JA','CALSCALE:GREGORIAN'];const now=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');for(const {e,day} of valid){const [s,t]=getTime(e,day);lines.push('BEGIN:VEVENT','UID:'+e.id+'-'+day+'@mobilitydlab.com','DTSTAMP:'+now,'DTSTART:'+stamp(day,s),'DTEND:'+stamp(day,t),'SUMMARY:'+escapeICS(e.title),'LOCATION:'+escapeICS(venues.get(e.venue).name+(e.room?' / '+e.room:'')),'DESCRIPTION:'+escapeICS(eventDescription(e)),'URL:'+rootURL+'?event='+encodeURIComponent(e.id)+'&date=any&on='+day,'STATUS:TENTATIVE','END:VEVENT');}lines.push('END:VCALENDAR');const blob=new Blob([lines.map(foldICS).join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='ramen-tech-2026-'+(valid.length===1?'event':'my-schedule')+'.ics';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);toast(`${valid.length}枠のカレンダーファイルを作成しました${entries.length>valid.length?'（時刻未公表・不一致の予定は除外）':''}`);}
async function share(eventOnly=false){const u=eventOnly&&detail?new URL(rootURL+'?event='+encodeURIComponent(detail.id)+'&date=any&on='+encodeURIComponent(detailDay)):stateURL();try{if(navigator.share){await navigator.share({title:'RAMEN TECH 2026 / 非公式ガイド',text:eventOnly&&detail?detail.title:'日付・会場・時間帯からイベントを検索。',url:u.href});return;}}catch(e){if(e.name==='AbortError')return;}try{await navigator.clipboard.writeText(u.href);toast(state.saved&&!eventOnly?'検索条件のURLをコピーしました。マイ予定の内容は共有されません。':'URLをコピーしました');}catch{$('#detail-body').innerHTML='<h2 id="detail-title">このURLをコピーして共有</h2><p class="detail-meta" style="overflow-wrap:anywhere;user-select:all">'+esc(u.href)+'</p>';if(!$('#detail-dialog').open)$('#detail-dialog').showModal();}}
$('#search').value=state.query;$('#venue-select').innerHTML='<option value="all">すべての会場</option>'+[...venues.values()].sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(v=>'<option value="'+esc(v.id)+'">'+esc(v.name)+(v.eventCount?' ('+v.eventCount+'枠)':' (予定未確認)')+'</option>').join('');$('#category-select').innerHTML='<option value="all">すべてのテーマ</option>'+Object.keys(colors).map(x=>'<option>'+esc(x)+'</option>').join('');
let inputTimer;$('#search').addEventListener('input',e=>{clearTimeout(inputTimer);if(e.isComposing)return;inputTimer=setTimeout(()=>change({query:e.target.value}),120);});$('#search').addEventListener('compositionend',e=>{clearTimeout(inputTimer);change({query:e.target.value});});$('#venue-select').addEventListener('change',e=>change({venue:e.target.value}));$('#category-select').addEventListener('change',e=>change({category:e.target.value}));$('#include-sessions').addEventListener('change',e=>change({sessions:e.target.checked}));$('#venue-search').addEventListener('input',e=>{venueState.query=e.target.value;venueState.limit=1000;venueRender();});
document.addEventListener('change',e=>{if(e.target.id==='detail-day'){detailDay=e.target.value;drawDetail();$('#detail-day')?.focus();}});
document.addEventListener('click',ev=>{const b=ev.target.closest('button,a');if(!b)return;const d=b.dataset;if(d.day){change({day:d.day});b.scrollIntoView({block:'nearest',inline:'nearest'});}if(d.order)change({order:d.order});if(d.venue)goVenue(d.venue);if(d.save)save(d.save,d.on);if(d.detail)openDetail(d.detail,d.on);if(d.role){venueState.role=d.role;venueState.limit=1000;venueRender();}if(b.id==='favorite-filter')change({...defaults,day:'any',saved:!state.saved,layout:state.layout});if(b.id==='load-more'){state.limit+=PAGE_SIZE;render();}if(b.id==='more-venues'){venueState.limit=1000;venueRender();}if(b.id==='download-saved'){if(window.RamenPlanner)window.RamenPlanner.exportPlan();else exportICS(events.filter(e=>saved.has(e.id)).flatMap(e=>e.dates.map(day=>({e,day}))));}if(b.id==='show-live'){const el=$('#live-container'),visible=el.hidden;el.hidden=!visible;b.setAttribute('aria-expanded',String(visible));b.textContent=visible?'公式時間割を閉じる ↑':'このページで公式時間割を表示 ↓';if(visible&&!el.querySelector('iframe')){const frame=document.createElement('iframe');frame.className='official-frame';frame.title='RAMEN TECH 2026 公式タイムテーブル（NappsTechnologies）';frame.referrerPolicy='strict-origin-when-cross-origin';frame.loading='lazy';frame.src='https://ramentech2026.aishain.com/';el.append(frame);}}
if(d.act==='reset')reset();if(d.act==='share')share();if(d.act==='garraway')goVenue('garraway');if(d.act==='saved'){change({...defaults,day:'any',saved:true,layout:state.layout});$('#search').value='';$('#schedule').scrollIntoView();}if(d.act==='close')$('#detail-dialog').close();if(d.act==='ics-one'&&detail)exportICS([{e:detail,day:detailDay}]);});
$('#detail-dialog').addEventListener('close',()=>{try{if(!['https:','http:'].includes(location.protocol))return;const u=new URL(location.href);u.searchParams.delete('event');u.searchParams.delete('on');history.replaceState(null,'',u.pathname+u.search+u.hash);}catch{}});
$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
const meta=data.meta;$('#stat-programs').textContent=events.length;$('#stat-venues').textContent=meta.venueCount;$$('[data-updated]').forEach(e=>e.textContent=meta.checkedAt.replace(/-/g,'.'));$('#coverage-text').textContent=`公式登録${meta.registrationEvents}件＋公式時間割${meta.timetableSlots}枠を照合。重複・仮時刻を整理し、主催者日程を補完。`;
$('#source-scope').textContent=`公式登録サイトの公開${meta.registrationEvents}件と、公式タイムテーブル${meta.timetableSlots}枠を照合。重複を整理し、Garraway Fの6つの独自企画・主催者が公表した関連日程を加え、${meta.eventCount}イベント枠と${meta.sessionCount}個別セッション枠を収録しています。確認日：${meta.checkedAt}。`;
const names=['RAMEN TECH公式登録','公式タイムテーブル','Global Summit','StartupGo!Go!','FFGみらいの会議','STARTUP KYUSHU','会場パートナー第1弾','会場・コワーキング第2弾','4th ISEE Asia'];$('#source-links').innerHTML=meta.sources.map((u,i)=>'<a href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">'+esc(names[i]||new URL(u).hostname)+' ↗</a>').join('')+'<a href="https://the-creator.jp/about.html" target="_blank" rel="noopener noreferrer">The Creators 開催概要 ↗</a>';

$('#area-select').innerHTML='<option value="all">すべてのエリア</option>'+[...new Set(data.venues.map(v=>v.area))].sort((a,b)=>a.localeCompare(b,'ja')).map(a=>'<option>'+esc(a)+'</option>').join('');
$('#time-select option[value="unknown"]').textContent='時刻未公表・要確認';
for(const [selector,key] of Object.entries({'#time-select':'period','#area-select':'area','#fee-select':'fee','#time-from':'from','#time-to':'until','#sort-select':'order'})){$(selector).addEventListener('change',e=>change({[key]:e.target.value}));}
$('#known-only').addEventListener('change',e=>change({known:e.target.checked}));
if(state.area!=='all'||state.fee!=='all'||state.known||state.from||state.until)$('#advanced-filters').open=true;
document.addEventListener('click',ev=>{const b=ev.target.closest('button,a');if(!b)return;const d=b.dataset;if(d.layout)change({layout:d.layout});if(d.query!==undefined){change({...defaults,day:'any',query:d.query,layout:state.layout});$('#search').focus({preventScroll:true});}if(d.clear){const v=d.clear==='day'?'any':defaults[d.clear];change({[d.clear]:v});}if(b.id==='clear-query'){clearTimeout(inputTimer);change({query:''});$('#search').focus({preventScroll:true});}if(b.id==='show-all'){state.limit=10000;render();}if(d.act==='widen')change({day:'any'});if(d.act==='share-event')share(true);});
window.addEventListener('popstate',()=>{state=readState();$('#search').value=state.query;render();});
$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();clearTimeout(inputTimer);change({query:e.target.value});$('#result-label').scrollIntoView({block:'center'});}});
render();venueRender();if(params.get('event'))openDetail(params.get('event'),params.get('on'));window.RamenGuide={data,openDetail,setSaved:(id,value)=>{value?saved.add(id):saved.delete(id);try{localStorage.setItem(KEY,JSON.stringify([...saved]));}catch{}render();},get state(){return state},filtered,getTime,canCalendar,exportICS,reset,change,stateURL,queryTerms,termMatch};
})();
