/* RAMEN TECH guide v3 — maintained source; assembled by prepare-live-guide.py.
 * Catalog remains source-of-truth. Bookmarks, occurrences and self-reported registrations are separate.
 * Time arithmetic is JST. Maps use catalog coordinates; dashed lines are visit order, never street routes.
 */
'use strict';
(()=>{
const CFG=window.GUIDE_CONFIG||{preview:true}, $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
let D=window.RAMEN_CATALOG;
if(!D||!Array.isArray(D.events)||!Array.isArray(D.venues)){ $('#event-list').innerHTML='<div class="empty-state"><h2>データを読み込めませんでした</h2><p>通信状態をご確認ください。公式サイトでも開催情報を確認できます。</p><a class="button" href="https://www.ramentech.jp/" rel="noopener noreferrer" target="_blank">公式サイトを開く</a></div>';return; }
const QA=new URLSearchParams(location.search).get('ui-test')==='1';
const ROOT='https://garrawayf.github.io/ramen-tech-2026/', KEY=QA?'ramen-guide-ui-test-v3':CFG.preview?'ramen-guide-preview-v3':'ramen-guide-v3', DEMO_KEY=QA?'ramen-guide-ui-test-demo-v3':'ramen-guide-preview-demo-v3';
let EV=new Map(D.events.map(e=>[e.id,e])), VEN=new Map(D.venues.map(v=>[v.id,v])), children=new Map();
function rebuildIndexes(){EV=new Map(D.events.map(e=>[e.id,e]));VEN=new Map(D.venues.map(v=>[v.id,v]));children=new Map();for(const e of D.events)if(e.parent&&EV.has(e.parent)){if(!children.has(e.parent))children.set(e.parent,[]);children.get(e.parent).push(e);}}
rebuildIndexes();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=s=>{try{const u=new URL(String(s));return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const link=(href,text,cls='')=>url(href)?`<a class="${esc(cls)}" href="${esc(url(href))}" target="_blank" rel="noopener noreferrer">${text}</a>`:'';
const norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96)).replace(/[‐‑–—]/g,'-').replace(/\s+/g,' ').trim();
const aliases={garraway:'ギャラウェイ ギャラウェー GarrawayF',one6:'ワンビル ONE FUKUOKA',cic:'ワンビル シーアイシー ONE FUKUOKA',daimyo:'大名カンファレンス',fgn:'グロースネクスト FGN'};
const syn=[['ai','人工知能','生成ai'],['交流','meetup','ミートアップ','networking','ネットワーキング'],['pitch','ピッチ'],['startup','スタートアップ','起業'],['art','アート'],['design','デザイン'],['education','教育'],['free','無料']].map(x=>x.map(norm));
const terms=q=>(q.match(/"[^"]+"|\S+/g)||[]).map(x=>norm(x.replace(/^"|"$/g,'')));
function contains(text,t){if(/^[a-z]{1,2}$/.test(t))return new RegExp('(^|[^a-z0-9])'+t+'(?=$|[^a-z0-9])').test(text);return text.includes(t)||text.replace(/[ ._-]/g,'').includes(t.replace(/[ ._-]/g,''));}
function matchTerm(text,t){return (syn.find(g=>g.includes(t))||[t]).some(x=>contains(text,x));}
const dataText=e=>norm([e.title,e.parentTitle,e.room,e.speaker,e.description,VEN.get(e.venue)?.name,VEN.get(e.venue)?.area,aliases[e.venue],e.category,e.fee,...(e.tags||[]),...(e.notes||[])].join(' '));
const dateOK=s=>/^2026-\d{2}-\d{2}$/.test(String(s))&&Number.isFinite(Date.parse(s+'T12:00:00+09:00'));
const dayName=(d,short=false)=>{if(!dateOK(d))return '日付未確認';const w=['日','月','火','水','木','金','土'][new Date(d+'T12:00:00+09:00').getUTCDay()];return `${+d.slice(5,7)}/${+d.slice(8,10)}${short?' '+w:'（'+w+'）'}`;};
const min=t=>/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(String(t))?+t.slice(0,2)*60+(+t.slice(3)):t==='24:00'?1440:null;
const time=n=>n===null||!Number.isFinite(n)?'未確認':`${n>=1440?'翌日 ':''}${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const inputTime=n=>n===1440?'24:00':time(n), slot=(e,d)=>e?.slots?.[d]||[e?.start||null,e?.end||null], k=(id,d)=>id+'|'+d;
function nowJST(){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return {day:`${p.year}-${p.month}-${p.day}`,minute:+p.hour*60+(+p.minute),clock:p.hour+':'+p.minute};}
const allDays=[...new Set(D.events.flatMap(e=>e.dates))].sort(), mainDays=['2026-10-07','2026-10-08','2026-10-09','2026-10-10','2026-10-11'];
const present=nowJST(), initialDay=mainDays.includes(present.day)?present.day:'2026-10-07';
function signature(e,day){return JSON.stringify([e.title,e.venue,e.room,day,...slot(e,day),e.calendarBlocked||false,e.status,e.fee,e.dates.includes(day)]);}
function newModel(){return {version:3,candidates:[],entries:{},legs:{},settings:{buffer:10,speed:70},day:initialDay,view:'timeline'};}
let storageOK=true;
function hydrate(raw){const m=newModel();if(!raw||raw.version!==3||typeof raw.entries!=='object'||raw.entries===null||Array.isArray(raw.entries))throw Error('対応していない予定ファイルです。');
 m.candidates=Array.isArray(raw.candidates)?[...new Set(raw.candidates.filter(id=>typeof id==='string'&&EV.has(id)))].slice(0,600):[];
 for(const [key,x] of Object.entries(raw.entries).slice(0,600)){if(!x||typeof x.id!=='string'||!dateOK(x.day)||key!==k(x.id,x.day))continue;m.entries[key]={id:x.id,day:x.day,start:min(x.start)!==null?x.start:'',end:min(x.end)!==null?x.end:'',title:String(x.title||'保存した予定').slice(0,600),venue:String(x.venue||''),snapshot:String(x.snapshot||'').slice(0,4000),reviewed:String(x.reviewed||'').slice(0,4000),registration:['unknown','pending','done','notrequired'].includes(x.registration)?x.registration:'unknown',partialConfirmed:x.partialConfirmed===true};}
 for(const [key,x] of Object.entries(raw.legs||{}).slice(0,600)){if(key.includes('|')&&key.includes('~')&&key.length<2400&&x&&['walking','transit','driving'].includes(x.mode)){m.legs[key]={mode:x.mode,minutes:Number.isInteger(x.minutes)&&x.minutes>=0&&x.minutes<=720?x.minutes:null,signature:String(x.signature||'').slice(0,2000)};}}
 m.settings.buffer=[0,5,10,15,20,30].includes(+raw.settings?.buffer)?+raw.settings.buffer:10;m.settings.speed=[50,70,90].includes(+raw.settings?.speed)?+raw.settings.speed:70;m.day=dateOK(raw.day)?raw.day:initialDay;m.view=raw.view==='table'?'table':'timeline';return m;
}
function load(key){try{const raw=localStorage.getItem(key);return raw?hydrate(JSON.parse(raw)):newModel();}catch(e){storageOK=false;return newModel();}}
let userModel=load(KEY), model=userModel, demo=false;
const baseFilters={day:initialDay,q:'',venue:'all',category:'all',area:'all',period:'all',fee:'all',from:'',until:'',known:false,kind:'grouped',candidates:false,sort:'time',layout:'list',limit:18};
let filters={...baseFilters},screen='explore',planFocus='',modalType='',pending=null,undo=null,toastTimer,exportScope='day',mapScope='results',mapArea='all',todayTestTime='10:30';
const mapViews=new Map(),scrollStates={};
function parseURL(){const p=new URLSearchParams(location.search),d=p.get('date');filters.day=d==='any'?'any':d==='all'?'main':d==='pre'||d==='after'?d:allDays.includes(d)?d:/^\d{1,2}$/.test(d||'')&&allDays.includes('2026-10-'+d.padStart(2,'0'))?'2026-10-'+d.padStart(2,'0'):initialDay;
 filters.q=(p.get('q')||'').slice(0,160);for(const [key,param] of [['venue','venue'],['category','theme'],['area','area'],['period','period'],['fee','fee']]){const value=p.get(param);if(value)filters[key]=value;}if(!VEN.has(filters.venue))filters.venue='all';if(!['all','morning','afternoon','evening','unknown'].includes(filters.period))filters.period='all';if(!['all','free','no-registration'].includes(filters.fee))filters.fee='all';if(p.get('sessions')==='0')filters.kind='events';if(p.get('kind')&&['grouped','events','sessions','all'].includes(p.get('kind')))filters.kind=p.get('kind');filters.from=min(p.get('from'))!==null?p.get('from'):'';filters.until=min(p.get('until'))!==null?p.get('until'):'';filters.known=p.get('known')==='1';if(['time','venue','relevance'].includes(p.get('order')))filters.sort=p.get('order');filters.layout=p.get('view')==='cards'?'cards':'list';
 const hash=location.hash.slice(1);screen=({schedule:'explore',planner:'plan',venues:'map','garraway-featured':'garraway'}[hash])||(['explore','plan','today','map','garraway'].includes(hash)?hash:(CFG.start||'explore'));
}
parseURL();
function toast(message,canUndo=false,showPlan=false){
 clearTimeout(toastTimer);
 $('#toast').innerHTML=`<span>${esc(message)}</span><div class="toast-actions">${showPlan?'<button data-action="go-plan">マイ予定を見る</button>':''}${canUndo?'<button data-action="undo">取り消す</button>':''}<button data-action="dismiss-toast" aria-label="通知を閉じる">×</button></div>`;
 $('#toast').classList.add('visible');
 if(!canUndo&&!showPlan)toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),8000);
}
function persist(){try{localStorage.setItem(demo?DEMO_KEY:KEY,JSON.stringify(model));storageOK=true;}catch{storageOK=false;}$('#storage-warning').hidden=storageOK;}
function counts(){ $$('[data-plan-count]').forEach(el=>el.textContent=Object.keys(model.entries).length);$$('[data-candidate-count]').forEach(el=>el.textContent=model.candidates.length);$('#sample-banner').hidden=!demo;$('#storage-warning').hidden=storageOK; }
function rememberUndo(){undo={model:structuredClone(model),demo};}
function changed(){persist();counts();renderCurrent();}
function empty(title,message,actionHTML=''){return `<div class="empty-state"><div class="empty-icon" aria-hidden="true">↗</div><h2>${esc(title)}</h2><p>${message}</p><div class="empty-actions">${actionHTML}</div></div>`;}
function displayScreen(next,{history=true,scroll=true}={}){if(!['explore','plan','today','map','garraway'].includes(next))next='explore';scrollStates[screen]=window.scrollY;screen=next;$$('.screen').forEach(el=>el.hidden=el.id!=='screen-'+next);$$('[data-screen]').forEach(b=>{if(b.dataset.screen===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});renderCurrent();if(history){try{const u=new URL(location.href);u.hash=next;window.history.replaceState(null,'',u);}catch{}}if(scroll)window.scrollTo(0,scrollStates[next]||0);document.title=(CFG.preview?'公開前プレビュー｜':'')+({explore:'探す',plan:'マイ予定',today:'当日ナビ',map:'会場マップ',garraway:'Garraway F'}[next])+'｜RAMEN TECH 2026 非公式回遊ガイド';}
function renderCurrent(){if(screen==='explore')renderExplore();else if(screen==='plan')renderPlan();else if(screen==='today')renderToday();else if(screen==='map')renderAllMap();else if(screen==='garraway')renderGF();}
function currentScope(d){if(filters.day==='any')return true;if(filters.day==='main')return mainDays.includes(d);if(filters.day==='pre')return d<'2026-10-07';if(filters.day==='after')return d>'2026-10-11';return d===filters.day;}
function knownTime(e,d){const [s,t]=slot(e,d);return min(s)!==null&&min(t)!==null&&min(t)>min(s)&&!e.calendarBlocked&&e.status!=='cancelled';}
function feeNoReg(e){return /予約不要|申込不要|登録不要/.test(e.fee||'');}
function isFlexible(e){return /入退場自由|出入り自由|途中入退場自由/.test((e.notes||[]).join(' '));}
function matches(e,d,{ignoreKind=false}={}){const v=VEN.get(e.venue)||{};if(!currentScope(d))return false;if(filters.venue!=='all'&&e.venue!==filters.venue)return false;if(filters.category!=='all'&&e.category!==filters.category)return false;if(filters.area!=='all'&&v.area!==filters.area)return false;if(filters.candidates&&!model.candidates.includes(e.id))return false;if(filters.fee==='free'&&!(e.fee||'').includes('無料'))return false;if(filters.fee==='no-registration'&&(!feeNoReg(e)||!(e.fee||'').includes('無料')))return false;if(!terms(filters.q).every(t=>matchTerm(dataText(e),t)))return false;
 if(!ignoreKind&&filters.kind==='events'&&e.kind!=='event')return false;if(!ignoreKind&&filters.kind==='sessions'&&e.kind!=='session')return false;const known=knownTime(e,d);if(filters.known&&!known)return false;if(filters.period==='unknown'&&known)return false;const [a,b]=slot(e,d),s=min(a),end=min(b);if(['morning','afternoon','evening'].includes(filters.period)){if(!known)return false;const [lo,hi]={morning:[0,720],afternoon:[720,1080],evening:[1080,1440]}[filters.period];if(!(s<hi&&end>lo))return false;}
 if(filters.from||filters.until){if(!known)return false;if(filters.from&&s<min(filters.from))return false;if(filters.until&&end>min(filters.until))return false;if(filters.from&&filters.until&&min(filters.from)>=min(filters.until))return false;}return true;}
function score(e){return terms(filters.q).reduce((v,t)=>v+(matchTerm(norm(e.title),t)?5:0)+(matchTerm(norm(e.category),t)?2:0),0);}
function occurrences(){let raw=D.events.flatMap(e=>e.dates.filter(d=>matches(e,d)).map(day=>({e,day,children:[]})));if(filters.kind==='grouped'){const out=new Map();for(const r of raw){const parent=r.e.parent&&EV.get(r.e.parent);if(parent&&parent.dates.includes(r.day)){const key=k(parent.id,r.day);if(!out.has(key))out.set(key,{e:parent,day:r.day,children:[],childMatch:true});out.get(key).children.push(r.e);}else{const key=k(r.e.id,r.day);if(out.has(key)){out.get(key).e=r.e;out.get(key).childMatch=false;}else out.set(key,r);}}
 for(const r of out.values()){const cs=(children.get(r.e.id)||[]).filter(e=>e.dates.includes(r.day)&&matches(e,r.day,{ignoreKind:true}));r.children=[...new Map([...r.children,...cs].map(e=>[e.id,e])).values()];}raw=[...out.values()];}
 return raw.sort((a,b)=>{if(filters.sort==='relevance'&&filters.q){const diff=score(b.e)-score(a.e);if(diff)return diff;}if(filters.sort==='venue'){const diff=(VEN.get(a.e.venue)?.name||'').localeCompare(VEN.get(b.e.venue)?.name||'','ja');if(diff)return diff;}return a.day.localeCompare(b.day)||(slot(a.e,a.day)[0]||'99:99').localeCompare(slot(b.e,b.day)[0]||'99:99')||a.e.title.localeCompare(b.e.title,'ja');});}
function registrationRequired(e){return !feeNoReg(e)&&/要参加登録|事前申込|要事前予約|要予約|申込必須/.test(e.fee||'');}
function feeBadge(e){
 const fee=e.fee||'',free=fee.includes('無料'),paid=/[\d,]+円/.test(fee);
 const price=free?'無料':paid?fee:'料金は要確認';
 const condition=feeNoReg(e)?'予約不要':registrationRequired(e)?'事前申込が必要':fee.includes('招待制')?'招待制':'申込条件は要確認';
 return `<span class="badge ${free?'green':''}" data-fee>${esc(price)}</span><span class="badge" data-registration-condition>${condition}</span>`;
}
function eventSummary(e){
 const lines=(e.description||'').split(/\n/).map(t=>t.trim()).filter(t=>t&&!/^(出典|種別|登壇者)\s*[:：]|https?:\/\//.test(t));
 const text=lines.join(' ').split(/(?<=。)/)[0]||'';
 return text.length>110?text.slice(0,109)+'…':text;
}
function statusBadges(e,day){let out='';if(e.status==='cancelled')out+='<span class="badge danger">中止表記</span>';else if(e.calendarBlocked)out+='<span class="badge danger">時刻情報が不一致</span>';else if(e.status==='soldout')out+='<span class="badge warn">完売表記・要確認</span>';else if(e.status==='check')out+='<span class="badge warn">開催条件を要確認</span>';if(!knownTime(e,day)&&!e.calendarBlocked&&e.status!=='cancelled')out+='<span class="badge warn">時刻未確定</span>';const v=VEN.get(e.venue);if(!v||['tbd','private','city','kyushu-venues','v-9c4fea060c'].includes(v.id))out+='<span class="badge warn">会場を要確認</span>';if(e.origin==='主催者予定')out+='<span class="badge pink">主催者予定</span>';return out;}
function cardHTML(e,day,cs=[],childMatch=false){
 const [a,b]=slot(e,day),v=VEN.get(e.venue),fav=model.candidates.includes(e.id),sel=!!model.entries[k(e.id,day)],parent=EV.get(e.parent),summary=eventSummary(e);
 return `<article class="event-card ${e.venue==='garraway'?'garraway':''} ${e.kind==='session'?'session-card':''}">
 <div class="event-clock"><p class="event-date">${dayName(day)}</p><p class="event-time">${esc(a||'時刻未公表')}${b?`<small>–${esc(b)}</small>`:''}</p><small class="event-kind">${e.kind==='session'?'個別セッション':e.dates.length>1?'複数日開催':'イベント'}</small></div>
 <div class="event-copy">${e.kind==='session'&&(parent||e.parentTitle)?`<p class="session-context">${esc(parent?.title||e.parentTitle)} 内の企画</p>`:''}<button class="card-title" data-detail="${esc(e.id)}" data-day="${day}">${esc(e.title)}</button>${summary?`<p class="event-summary">${esc(summary)}</p>`:''}
 <p class="event-place">${esc(v?.name||'会場要確認')}<span class="area">${esc(v?.area||'')}</span></p>
 <div class="badges">${feeBadge(e)}${statusBadges(e,day)}</div>${childMatch?'<p class="source-hint">中のセッションが条件に一致しています。イベント全体の時間は異なる場合があります。</p>':''}</div>
 <div class="card-actions"><button class="candidate-button" data-candidate="${esc(e.id)}" aria-pressed="${fav}" aria-label="${esc(e.title)}を${fav?'気になるから外す':'気になるに保存'}">${fav?'♥ 気になる':'♡ 気になる'}</button><button class="add-button" data-add="${esc(e.id)}" data-day="${day}" aria-pressed="${sel}">${sel?'✓ 行く予定に追加済み':'＋ 行く予定に入れる'}</button></div>
 ${cs.length?`<details class="nested-sessions" ${childMatch?'open':''}><summary>中のセッションを見る（${cs.length}件）</summary><div class="session-list">${[...cs].sort((a,b)=>(slot(a,day)[0]||'99').localeCompare(slot(b,day)[0]||'99')).map(c=>`<div class="session-mini"><button class="title-button" data-detail="${esc(c.id)}" data-day="${day}"><span class="mini-time">${esc(slot(c,day).filter(Boolean).join('–')||'時刻未公表')}</span>${esc(c.title)}</button><button class="small-button" data-add="${esc(c.id)}" data-day="${day}" aria-pressed="${!!model.entries[k(c.id,day)]}">${model.entries[k(c.id,day)]?'✓ 追加済み':'＋ 行く予定'}</button></div>`).join('')}</div></details>`:''}</article>`;
}
function drawDayTabs(){let choices=[['any','全日程',''],...mainDays.map(d=>[d,`${+d.slice(5,7)}/${+d.slice(8)}`,dayName(d,true).slice(-1)])];if(allDays.includes(filters.day)&&!mainDays.includes(filters.day))choices.push([filters.day,dayName(filters.day,true),'']);$('#day-tabs').innerHTML=choices.map(([d,label,w])=>`<button class="day-tab" data-date="${d}" aria-pressed="${filters.day===d}">${label}${w?'<small>'+w+'</small>':''}</button>`).join('')+`<button class="day-tab related" data-action="related-dates" aria-pressed="${['pre','after','main'].includes(filters.day)}">${filters.day==='pre'?'前日程':filters.day==='after'?'後日程':filters.day==='main'?'本会期5日間':'関連日程'} ▾</button>`;}
function filterPairs(){return Object.entries({venue:filters.venue!=='all'?VEN.get(filters.venue)?.name:'',category:filters.category!=='all'?filters.category:'',area:filters.area!=='all'?filters.area:'',period:filters.period!=='all'?({morning:'午前',afternoon:'午後',evening:'夕方から（18時〜）',unknown:'時刻未確定'})[filters.period]:'',fee:filters.fee!=='all'?filters.fee==='free'?'無料':'無料・予約不要':'',from:filters.from?filters.from+'以降':'',until:filters.until?filters.until+'まで':'',known:filters.known?'時刻確認済み':'',kind:filters.kind!=='grouped'?({events:'イベントのみ',sessions:'セッションのみ',all:'セッション独立表示'})[filters.kind]:'',candidates:filters.candidates?'♡ 気になるのみ':''}).filter(([,v])=>v);}
function renderExplore(){drawDayTabs();
 $$('[data-quick]').forEach(b=>{const [key,value]=b.dataset.quick.split(':');b.setAttribute('aria-pressed',filters[key]===value);});
 const scope=({any:'全日程',main:'本会期',pre:'前日程',after:'後日程'})[filters.day]||dayName(filters.day);
 $('#filter-summary').textContent=[scope,...filterPairs().map(([,label])=>label)].join('・')+' のイベント';
 $('#time-context').hidden=!(filters.from||filters.until);$('#query').value=filters.q;$('#sort').value=filters.sort;$('#clear-query').hidden=!filters.q;const fp=filterPairs();$('#filter-count').textContent=fp.length?String(fp.length):'';$('#candidate-toggle').setAttribute('aria-pressed',filters.candidates);let chips=[];if(filters.q)chips.push(['q','「'+filters.q+'」の検索結果']);chips.push(...fp);$('#active-filters').innerHTML=chips.map(([key,label])=>`<button data-clear-filter="${key}">${esc(label)} ×</button>`).join('')+(chips.length?'<button class="reset" data-action="reset-filters">条件を解除</button>':'');const rows=occurrences();renderContextGF(rows);$('#result-count').innerHTML=`<strong>${rows.length}</strong>${filters.kind==='grouped'?'イベント枠':'件'}${filters.candidates?'の候補':''}${filters.day==='any'?' / 全日程':filters.day==='main'?' / 本会期':filters.day==='pre'?' / 前日程':filters.day==='after'?' / 後日程':' / '+dayName(filters.day)}`;
 $('#event-list').className='event-list'+(filters.layout==='cards'?' grid':'');$('#layout-toggle').textContent=filters.layout==='cards'?'☰ 一覧':'▦ カード';$('#layout-toggle').setAttribute('aria-label',filters.layout==='cards'?'一覧表示に切り替え':'カード表示に切り替え');let day='';$('#event-list').innerHTML=rows.slice(0,filters.limit).map(r=>{let head='';if(day!==r.day&&['any','main','pre','after'].includes(filters.day)){head=`<h2 class="date-heading">${dayName(r.day)}</h2>`;day=r.day;}return head+cardHTML(r.e,r.day,r.children,r.childMatch);}).join('')||empty(filters.candidates?'候補がありません':'条件に合うイベントがありません',filters.candidates?'♡は比較用のメモです。候補から外してもマイ予定は消えません。':'日付や絞り込みを変えて探してみてください。',`<button class="button primary" data-action="reset-filters">絞り込みを解除</button><button class="button secondary" data-date="any">全日程を見る</button>`);$('#load-more').hidden=rows.length<=filters.limit;$('#load-more').textContent=`続きを見る（残り${Math.max(0,rows.length-filters.limit)}枠）`;counts();}
function updateURL(){try{const u=new URL(location.href);u.search='';if(QA)u.searchParams.set('ui-test','1');u.searchParams.set('date',filters.day==='main'?'all':filters.day);for(const [key,p] of [['q','q'],['venue','venue'],['category','theme'],['area','area'],['period','period'],['fee','fee'],['from','from'],['until','until'],['kind','kind'],['sort','order']])if(filters[key]&&filters[key]!==baseFilters[key])u.searchParams.set(p,filters[key]);if(filters.known)u.searchParams.set('known','1');if(filters.layout==='cards')u.searchParams.set('view','cards');u.hash='explore';history.replaceState(null,'',u);}catch{}}
function filterChanged(){filters.limit=18;renderExplore();updateURL();}
function toggleCandidate(id){
 if(!EV.has(id))return;const yes=model.candidates.includes(id),first=!model.candidates.length&&!Object.keys(model.entries).length;
 model.candidates=yes?model.candidates.filter(x=>x!==id):[...model.candidates,id];changed();
 if(modalType==='detail'&&pending?.id===id)detail(id,pending.day);
 toast(yes?'「気になる」から外しました。': '「気になる」に保存しました。'+(first?'この端末・ブラウザに保存されます。':''));
}
function makeEntry(e,day){return {id:e.id,day,start:'',end:'',title:e.title,venue:e.venue,snapshot:signature(e,day),reviewed:'',registration:feeNoReg(e)?'notrequired':'unknown',partialConfirmed:false};}
function relationEntries(id,day){const e=EV.get(id);return Object.entries(model.entries).filter(([,x])=>x.day===day&&(x.id===e?.parent||EV.get(x.id)?.parent===id));}
function add(id,day,opts={}){const e=EV.get(id);if(!e||!e.dates.includes(day))return;const key=k(id,day);if(model.entries[key]){remove(key);if(modalType==='detail')detail(id,day);return;}
 const relatives=relationEntries(id,day);if(relatives.length&&!opts.force){pending={type:'related',id,day,keys:relatives.map(([key])=>key),times:opts.times};openModal('related','イベント全体とセッションの重複',`<p class="modal-intro">同じイベントに含まれる予定が、すでにこの日に入っています。セッションだけに入れ替えると、重複せずに行程を組めます。</p><div class="notice">${relatives.map(([,x])=>esc(EV.get(x.id)?.title||x.title)).join('<br>')}</div><div class="merge-choice"><button class="button primary" data-action="replace-related">既存の枠と入れ替えて追加</button><button class="button secondary" data-action="keep-related">両方を残す（重複の警告を表示）</button><button class="button secondary" data-action="close-modal">戻る</button></div>`);return;}
 const first=!model.candidates.length&&!Object.keys(model.entries).length;rememberUndo();if(opts.removeKeys)opts.removeKeys.forEach(key=>delete model.entries[key]);const x=makeEntry(e,day);if(opts.times){x.start=opts.times[0];x.end=opts.times[1];x.partialConfirmed=isFlexible(e);}model.entries[key]=x;model.day=day;changed();if(modalType==='detail')closeModal();toast(dayName(day)+'のマイ予定に追加しました。'+(registrationRequired(e)?'参加には主催者サイトでの申込が必要です。':feeNoReg(e)?'':'参加条件は主催者サイトで確認してください。')+(first?'この端末・ブラウザに保存されます。':''),true,true);}
function remove(key){if(!model.entries[key])return;rememberUndo();delete model.entries[key];if(planFocus===key)planFocus='';changed();toast('この日の予定だけを外しました。候補はそのままです。',true);}
function daysInPlan(){return [...new Set(Object.values(model.entries).map(x=>x.day))].sort();}
function dayRows(day){return Object.entries(model.entries).filter(([,x])=>x.day===day).map(([key,x])=>{const e=EV.get(x.id),v=VEN.get(e?.venue||x.venue),missing=!e||!e.dates.includes(day),[ps,pe]=missing?[null,null]:slot(e,day),s=min(x.start||ps),t=min(x.end||pe),invalid=missing||s===null||t===null||t<=s||!knownTime(e,day)||s<min(ps)||t>min(pe),changed=!missing&&signature(e,day)!==x.snapshot,needsReview=!missing&&['check','soldout'].includes(e.status)&&x.reviewed!==signature(e,day),needsPartialReview=!missing&&!!(x.start||x.end)&&!isFlexible(e)&&!x.partialConfirmed;return {key,x,e,venue:v,day,start:s,end:t,sourceStart:ps,sourceEnd:pe,missing,invalid,changed,needsReview,needsPartialReview};}).sort((a,b)=>(a.invalid?1:0)-(b.invalid?1:0)||(a.start??99999)-(b.start??99999)||a.key.localeCompare(b.key));}
function geo(v){const p=v?.geo;return p&&p.status==='located'&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<85&&Math.abs(p.lng)<=180?p:null;}
function distance(a,b){const r=Math.PI/180,q=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lng-a.lng)*r/2)**2;return 6371000*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
function venueLocation(v){return v?(v.geo?.address||[v.name,v.area==='その他'?'':v.area,'福岡'].filter(Boolean).join(' ')):'会場未確認';}
function placeLink(v){const u=new URL('https://www.google.com/maps/search/');u.search=new URLSearchParams({api:'1',query:venueLocation(v)});return u.href;}
function directions(a,b,mode='walking'){const u=new URL('https://www.google.com/maps/dir/');const p={api:'1',destination:venueLocation(b),travelmode:mode};if(a)p.origin=venueLocation(a);u.search=new URLSearchParams(p);return u.href;}
function legSig(a,b){return JSON.stringify([a.venue?.id,a.e?.room,b.venue?.id,b.e?.room,geo(a.venue)?[geo(a.venue).lat,geo(a.venue).lng,geo(a.venue).address]:null,geo(b.venue)?[geo(b.venue).lat,geo(b.venue).lng,geo(b.venue).address]:null]);}
function estimate(a,b,mode='walking'){if(mode!=='walking')return {minutes:null,method:'地図で所要時間を確認して入力',distance:null};const unknown=['tbd','private','city','kyushu-venues','v-9c4fea060c'];if(a?.id===b?.id&&a&&!unknown.includes(a.id))return {minutes:0,method:'同じ会場・移動なし（受付の予備は別）',distance:0};const ap=geo(a),bp=geo(b);if(!ap||!bp)return {minutes:null,method:'会場の位置を確認して入力',distance:null};const d=distance(ap,bp);if(d>5000)return {minutes:null,method:'長距離のため地図で確認して入力',distance:d};if(d<35)return {minutes:5,method:'同じ建物付近・館内移動の目安',distance:d};return {minutes:Math.max(5,Math.ceil(d*1.35/model.settings.speed/5)*5),method:'直線距離×1.35から算出した徒歩の目安',distance:d};}
function transfer(a,b){const key=a.key+'~'+b.key,stored=model.legs[key],sig=legSig(a,b),mode=stored?.mode||'walking',manual=stored?.minutes!==null&&stored?.minutes!==undefined&&stored.signature===sig,base=estimate(a.venue,b.venue,mode);return {key,from:a,to:b,mode,signature:sig,manual,stale:!!stored&&stored.minutes!==null&&!manual,minutes:manual?stored.minutes:base.minutes,method:manual?'自分で確認した所要時間':base.method,distance:base.distance,url:directions(a.venue,b.venue,mode)};}
function itinerary(day){const rows=dayRows(day),ordered=rows.filter(r=>!r.invalid),unresolved=rows.filter(r=>r.invalid),legs=[],gaps=[],issues=[];for(const r of rows){if(r.invalid)issues.push({type:'invalid',key:r.key,text:invalidReason(r)});if(r.changed)issues.push({type:'changed',key:r.key,text:'保存後に開催情報が変わっています'});if(r.needsPartialReview)issues.push({type:'partial',key:r.key,text:'途中入退場の可否を確認してください'});if(r.needsReview)issues.push({type:'review',key:r.key,text:'開催・参加条件の確認が必要です'});}
 let ready=null;for(let i=0;i<ordered.length;i++){const r=ordered[i];r.number=i+1;r.late=0;if(i===0){ready=r.end;continue;}const prev=ordered[i-1],leg=transfer(prev,r);leg.depart=ready;leg.arrive=ready!==null&&leg.minutes!==null?ready+leg.minutes:null;leg.buffer=model.settings.buffer;leg.free=leg.arrive!==null?r.start-leg.arrive-leg.buffer:null;leg.overlap=Math.max(0,prev.end-r.start);r.late=leg.free!==null?Math.max(0,-leg.free):null;legs.push(leg);if(leg.minutes===null||leg.arrive===null)issues.push({type:'move',key:leg.key,text:'移動時間が未確認の区間があります'});else if(leg.free<0)issues.push({type:'conflict',key:r.key,legKey:leg.key,text:`移動・予備時間が${-leg.free}分不足しています`});if(leg.stale)issues.push({type:'move',key:leg.key,text:'会場変更のため、手入力の移動時間を再確認してください'});if(leg.free>0)gaps.push({key:leg.key,from:prev,to:r,start:leg.arrive+leg.buffer,end:r.start,minutes:leg.free});ready=leg.arrive===null?null:Math.max(r.end,leg.arrive+leg.buffer);}
 // Detect nonadjacent temporal overlaps too; keeping a parent plus its session is deliberate but never silent.
 for(let i=0;i<ordered.length;i++)for(let j=i+1;j<ordered.length;j++){const a=ordered[i],b=ordered[j];if(a.start<b.end&&b.start<a.end&&!issues.some(x=>x.type==='conflict'&&x.key===b.key))issues.push({type:'conflict',key:b.key,text:'参加時間が重なっている予定があります'});}
 return {day,rows,ordered,unresolved,legs,gaps,issues,travel:legs.reduce((v,l)=>v+(l.minutes||0),0),unknown:legs.filter(l=>l.minutes===null).length,free:gaps.reduce((s,g)=>s+g.minutes,0)};
}
function planItems(p){return [...p.ordered.map(r=>({key:r.key,venue:r.venue,title:r.e?.title||r.x.title,number:r.number,start:r.start})),...p.unresolved.map(r=>({key:r.key,venue:r.venue,title:r.e?.title||r.x.title,number:'?',start:null,unordered:true}))];}
function mapHTML(id,items,title='訪問順のマップ',sub='予定と同じ番号で、会場を表示',route=true){const known=items.filter(x=>geo(x.venue)),unknown=items.filter(x=>!geo(x.venue));return `<section class="map-panel" id="${id}" data-map-panel="${id}" aria-label="${esc(title)}"><div class="map-heading"><div><h2>${title}</h2><p>${sub}</p></div><div class="map-display-select" role="group" aria-label="地図の背景"><button data-map-mode="diagram" data-map="${id}" aria-pressed="true">位置図</button><button data-map-mode="road" data-map="${id}" aria-pressed="false">道路地図 ↗</button></div></div><div class="geo-map" tabindex="0" role="group" aria-label="会場地図。上下左右キーで移動、プラス・マイナスで拡大縮小。"><div class="map-tiles"></div><svg class="map-lines" aria-hidden="true"></svg><div class="map-markers"></div><span class="map-north">N<b>↑</b></span><div class="map-controls"><button data-map-zoom="1" data-map="${id}" aria-label="地図を拡大">＋</button><button data-map-zoom="-1" data-map="${id}" aria-label="地図を縮小">−</button><button data-map-fit="${id}" aria-label="全会場を地図に収める">全体</button></div><div class="map-scale"></div><span class="map-attribution">会場位置：掲載データ</span></div><div class="map-status">${known.length?'会場座標による位置図。':'表示できる会場座標がありません。'}${route?'破線は訪問順で、実際の歩行経路ではありません。':'実際の道順は経路リンクで確認してください。'}</div>${unknown.length?`<div class="map-unknown">位置未確認 ${unknown.length}件：${unknown.map(x=>esc(x.venue?.name||'会場未確認')).join('、')}。地図上の訪問順には含めていません。</div>`:''}<div class="map-legend"><span><i></i>訪問先</span><span><i class="gf"></i>Garraway F</span><span>番号をタップして詳細（？は順序未定）</span></div><div class="map-selected" hidden></div>${route?`<div class="map-route-list">${items.map(x=>`<button class="map-route-row" data-map-item="${esc(x.key)}" data-map="${id}"><span class="stop-number">${x.number}</span><span>${esc(x.venue?.name||'会場要確認')}</span><small>${time(x.start)}</small></button>`).join('')}</div>`:''}</section>`;}
class VenueMap{
 constructor(id,items,route=true){this.id=id;this.root=document.getElementById(id);this.el=this.root?.querySelector('.geo-map');this.items=items;this.route=route;this.mode='diagram';this.zoom=16;this.center=[0,0];this.selected=null;this.tilesGeneration=0;if(!this.el)return;this.fit();this.el.addEventListener('keydown',e=>{const delta={ArrowLeft:[-80,0],ArrowRight:[80,0],ArrowUp:[0,-80],ArrowDown:[0,80]}[e.key];if(delta&&e.target===this.el){e.preventDefault();this.center=[this.center[0]+delta[0],this.center[1]+delta[1]];this.draw();}else if(['+','=','-'].includes(e.key)&&e.target===this.el){e.preventDefault();this.changeZoom(e.key==='-'?-1:1);}});let start=null;this.el.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.target.closest('button,a'))return;start=[e.clientX,e.clientY,...this.center];this.el.setPointerCapture(e.pointerId);});this.el.addEventListener('pointermove',e=>{if(!start)return;this.center=[start[2]-(e.clientX-start[0]),start[3]-(e.clientY-start[1])];this.draw(false);});this.el.addEventListener('pointerup',()=>{if(start){start=null;this.draw();}});this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(this.el);}
 destroy(){this.resize?.disconnect();this.tilesGeneration++;}
 project(p,z=this.zoom){const n=256*2**z,s=Math.sin(p.lat*Math.PI/180);return [(p.lng+180)/360*n,(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*n];}
 unproject(x,y){const n=256*2**this.zoom;return {lng:x/n*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*y/n)))*180/Math.PI};}
 fit(){const pts=this.items.map(x=>geo(x.venue)).filter(Boolean);const w=this.el.clientWidth||450,h=this.el.clientHeight||315;if(!pts.length){this.zoom=14;this.center=this.project({lat:33.590,lng:130.399});return this.draw();}if(pts.length===1){this.zoom=16;this.center=this.project(pts[0]);return this.draw();}for(let z=17;z>=3;z--){const arr=pts.map(p=>this.project(p,z)),xs=arr.map(x=>x[0]),ys=arr.map(x=>x[1]);if(Math.max(...xs)-Math.min(...xs)<w-130&&Math.max(...ys)-Math.min(...ys)<h-58||z===3){this.zoom=z;this.center=[(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2];break;}}this.draw();}
 changeZoom(d){const old=this.zoom;this.zoom=Math.max(3,Math.min(19,old+d));const factor=2**(this.zoom-old);this.center=this.center.map(x=>x*factor);this.draw();}
 position(p){const [x,y]=this.project(p);return [x-this.center[0]+this.el.clientWidth/2,y-this.center[1]+this.el.clientHeight/2];}
 setMode(mode){if(mode==='road'&&location.protocol==='file:'){const c=this.unproject(...this.center);const href=`https://www.openstreetmap.org/#map=${this.zoom}/${c.lat.toFixed(6)}/${c.lng.toFixed(6)}`;window.open(href,'_blank','noopener,noreferrer');toast('道路地図を別タブで開きます。確認版の位置図・予定はそのままです。');return;}this.mode=mode;this.root.querySelectorAll('[data-map-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mapMode===mode));this.draw();}
 draw(loadTiles=true){if(!this.el||!this.el.isConnected)return;const w=this.el.clientWidth||450,h=this.el.clientHeight||315,groups=new Map();this.items.forEach((item,i)=>{const p=geo(item.venue);if(!p)return;const key=p.lat.toFixed(5)+','+p.lng.toFixed(5);if(!groups.has(key))groups.set(key,{p,items:[],key});groups.get(key).items.push(item);});this.groups=[];for(const g of groups.values()){const pos=this.position(g.p);const near=this.groups.find(a=>{const q=this.position(a.p);return Math.hypot(q[0]-pos[0],q[1]-pos[1])<54;});if(near){const n=near.items.length,m=g.items.length;near.p={lat:(near.p.lat*n+g.p.lat*m)/(n+m),lng:(near.p.lng*n+g.p.lng*m)/(n+m)};near.items.push(...g.items);near.clustered=true;}else this.groups.push(g);}
 const nodes=this.items.map(x=>!x.unordered&&geo(x.venue)?this.position(geo(x.venue)):null);let path='';if(this.route)for(let i=1;i<nodes.length;i++){const a=nodes[i-1],b=nodes[i];if(a&&b&&Math.hypot(a[0]-b[0],a[1]-b[1])>2)path+=`M${a[0].toFixed(1)},${a[1].toFixed(1)} L${b[0].toFixed(1)},${b[1].toFixed(1)} `;}
 this.el.querySelector('.map-lines').setAttribute('viewBox',`0 0 ${w} ${h}`);this.el.querySelector('.map-lines').innerHTML=`<defs><marker id="arrow-${this.id}" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 L10 5 L0 10Z" fill="#255a9e"/></marker></defs><path class="map-route" d="${path}" marker-mid="url(#arrow-${this.id})"/>`;
 this.el.querySelector('.map-markers').innerHTML=this.groups.map((g,index)=>{const [x,y]=this.position(g.p);if(x< -70||x>w+70||y< -60||y>h+60)return '';const gf=g.items.every(x=>x.venue.id==='garraway'),labels=g.items.map(x=>x.number),active=g.items.some(x=>x.key===this.selected),name=[...new Set(g.items.map(x=>x.venue.name))].join(' / ');let friendly=g.clustered?'近接する'+new Set(g.items.map(x=>x.venue.id)).size+'会場':name.replace('ONE FUKUOKA CONFERENCE HALL / 6F','ONE FUKUOKA 6F').replace('サーブコープ 福岡天神フコク生命ビル15階','サーブコープ／天神15F');return `<button class="map-pin ${gf?'gf':''} ${active?'active':''}" style="left:${x}px;top:${y}px" data-map-group="${index}" data-map="${this.id}" aria-label="${esc(labels.join('・')+'番 '+name)}">${esc(labels.join('・'))}</button><span class="map-label" style="left:${Math.max(65,Math.min(w-65,x))}px;top:${y>h-65?y-76:y}px">${esc(friendly)}</span>`;}).join('');
 const c=this.unproject(...this.center),metersPerPixel=156543.03392*Math.cos(c.lat*Math.PI/180)/2**this.zoom,target=metersPerPixel*75,scale=[10,20,50,100,200,500,1000,2000,5000,10000,50000,100000].reduce((a,b)=>Math.abs(b-target)<Math.abs(a-target)?b:a);this.el.querySelector('.map-scale').innerHTML=`<i style="width:${Math.max(20,scale/metersPerPixel).toFixed(0)}px"></i>${scale>=1000?scale/1000+' km':scale+' m'}`;
 if(this.mode==='diagram'){this.el.querySelector('.map-tiles').innerHTML='';this.el.querySelector('.map-attribution').textContent='会場位置：掲載データ';this.root.querySelector('.map-status').textContent='会場座標による位置図。'+(this.route?'破線は訪問順で、実際の歩行経路ではありません。':'道順・入口は経路リンクで確認してください。');this.tilesGeneration++;}else if(loadTiles)this.loadTiles();}
 loadTiles(){const target=this.el.querySelector('.map-tiles'),w=this.el.clientWidth,h=this.el.clientHeight,left=this.center[0]-w/2,top=this.center[1]-h/2,generation=++this.tilesGeneration,z=this.zoom,n=2**z;target.innerHTML='';this.root.querySelector('.map-status').textContent='道路地図を読み込み中。破線は訪問順で、歩行経路ではありません。';this.el.querySelector('.map-attribution').innerHTML='© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a> contributors';let loaded=0,failed=0;for(let x=Math.floor(left/256);x<=Math.floor((left+w)/256);x++)for(let y=Math.max(0,Math.floor(top/256));y<=Math.min(n-1,Math.floor((top+h)/256));y++){const img=document.createElement('img');img.alt='';img.style.left=(x*256-left)+'px';img.style.top=(y*256-top)+'px';img.referrerPolicy='strict-origin-when-cross-origin';img.onload=()=>{if(generation!==this.tilesGeneration)return;loaded++;this.root.querySelector('.map-status').textContent='破線は会場の訪問順です。実際の道順・入口は「経路を確認」で確認してください。';};img.onerror=()=>{if(generation!==this.tilesGeneration)return;failed++;if(!loaded)this.root.querySelector('.map-status').textContent='道路地図を読み込めません。会場の座標・訪問順を位置図上に表示しています。';};const template=CFG.tileURL||'https://tile.openstreetmap.org/{z}/{x}/{y}.png';img.src=template.replace('{z}',String(z)).replace('{x}',String((x+n)%n)).replace('{y}',String(y));target.appendChild(img);}}
 selectGroup(index){const g=this.groups[index];if(!g)return;const area=this.root.querySelector('.map-selected');area.hidden=false;area.innerHTML=g.items.map(it=>`<p><strong>${it.number}｜${esc(it.venue.name)}</strong><br>${time(it.start)} ${esc(it.title)}</p><div class="detail-actions">${model.entries[it.key]?`<button class="button secondary" data-focus-plan="${esc(it.key)}">この予定へ</button>`:`<button class="button secondary" data-search-venue="${esc(it.venue.id)}">この会場のイベント</button>`}${link(directions(null,it.venue),'ここへの経路 ↗','button secondary')}</div>`).join('');this.selected=g.items[0].key;this.draw(false);}
 selectKey(key){const index=this.groups.findIndex(g=>g.items.some(x=>x.key===key));if(index>=0)this.selectGroup(index);}
}
function mountMap(id,items,route=true){mapViews.get(id)?.destroy();const m=new VenueMap(id,items,route);mapViews.set(id,m);return m;}
function regLabel(r){const reg=r.x.registration;if(reg==='done')return '✓ 申込済み（自己申告）';if(reg==='notrequired')return feeNoReg(r.e||{})?'予約不要':'申込不要（自己申告）';if(reg==='pending')return '申込がまだ';return '申込状況を確認';}
function planEventHTML(r){const e=r.e,own=e?.venue==='garraway';return `<article class="plan-event ${own?'garraway':''} ${planFocus===r.key?'focused':''}" id="stop-${esc(r.key)}" data-stop-key="${esc(r.key)}"><div class="plan-time">${r.invalid?'未定':time(r.start)}<small>${r.invalid?'':time(r.end)}</small></div><div class="plan-event-card"><div class="plan-event-header"><span class="stop-id"><b class="stop-number">${r.number||'?'}</b><span>${own?'GARRAWAY F':'EVENT'}</span><span class="stop-area">${esc(r.venue?.area||'')}</span></span><button class="remove-button" data-remove="${esc(r.key)}" aria-label="${esc(e?.title||r.x.title)}をこの日の予定から外す">×</button></div><h3>${esc(e?.title||r.x.title)}</h3><button class="venue-button" data-show-stop="${esc(r.key)}">◇ ${esc(r.venue?.name||'会場を要確認')} ↗</button>${e?.room?`<p class="event-room">${esc(e.room)}</p>`:''}${r.x.start||r.x.end?`<p class="visit-line">自分の参加時間 ／ 開催 ${esc(r.sourceStart)}–${esc(r.sourceEnd)}</p>`:''}${r.invalid?`<div class="plan-warning error">${r.missing?'保存した開催日が現在のデータにありません。':'時刻未公表・情報の不一致・中止などのため、行程計算とカレンダー出力の対象外です。'}${e?`<button data-detail="${esc(e.id)}" data-day="${r.day}">詳細を確認</button>`:''}</div>`:''}${r.needsPartialReview?`<div class="plan-warning">途中入退場の可否を確認してください。<button data-edit-time="${esc(r.key)}">確認して調整</button></div>`:''}${r.late>0?`<div class="plan-warning error">移動と予備時間を含めると${r.late}分不足。参加する時間を見直してください。</div>`:''}${r.changed?`<div class="plan-warning">保存後に開催情報が変わりました。<button data-review="${esc(r.key)}">変更内容を確認</button></div>`:''}${r.needsReview?`<div class="plan-warning">${e.status==='soldout'?'完売表記があります。主催者の案内で確認してください。':'開催条件に要確認の情報があります。'}<button data-review="${esc(r.key)}">内容を確認</button></div>`:''}<div class="plan-event-foot"><button class="registration ${['unknown','pending'].includes(r.x.registration)?'unknown':''}" data-registration="${esc(r.key)}">${regLabel(r)}</button>${!r.invalid?`<button data-edit-time="${esc(r.key)}">参加時間を調整</button>`:''}${e?`<button data-detail="${esc(e.id)}" data-day="${r.day}">詳細・主催者案内 ↗</button>`:''}</div></div></article>`;}
function legHTML(l){const mode={walking:'徒歩',transit:'公共交通',driving:'車・タクシー'}[l.mode];return `<div class="plan-leg ${l.free===null||l.free<0?'invalid':''}" data-leg-key="${esc(l.key)}"><h4><span>↳ ${mode} <strong>${l.minutes===null?'要確認':(l.manual?'':'約 ')+l.minutes+'分'}</strong></span><span class="badge ${l.minutes===null?'warn':'blue'}">${l.minutes===null?'未入力':l.manual?'確認して入力':'概算'}</span></h4><p class="leg-label">${l.minutes===0?'同じ会場・移動なし':l.manual?'手入力の所要時間':l.minutes!==null?'実際の経路は地図で確認':'所要時間を確認して入力してください'} ／ 予備 ${l.buffer}分</p><div class="leg-actions"><button data-edit-leg="${esc(l.key)}">移動方法・時間を変更</button>${link(l.url,'経路を確認 ↗')}</div><p class="leg-result">${l.free===null?'⚠ 到着見込みは未計算です':l.free<0?`⚠ 予備を含め ${-l.free}分不足${l.overlap?'（予定も'+l.overlap+'分重複）':''}`:`${time(l.depart)}出発 → ${time(l.arrive)}到着の目安`}</p></div>`;}
function gapHTML(g){return `<div class="plan-gap"><div><h4>${time(g.start)}–${time(g.end)}　空き ${g.minutes}分</h4><p>休憩・食事・もうひとつの出会いに。</p></div><div class="gap-actions"><button data-search-gap="${esc(g.key)}">この時間に参加できるイベントを探す</button><button class="text-button" data-gap="${esc(g.key)}">前後の移動も考えた候補を見る</button></div></div>`;}
function searchGap(key){
 const g=daysInPlan().flatMap(d=>itinerary(d).gaps).find(g=>g.key===key);
 if(!g){toast('予定が変わりました。最新の空き時間をご確認ください。');return;}
 filters={...baseFilters,day:g.from.day,from:inputTime(g.start),until:inputTime(g.end),known:true};
 closeModal();displayScreen('explore',{scroll:false});filterChanged();document.querySelector('.search-area').scrollIntoView({block:'start'});
}
function invalidReason(r){
 if(r.missing)return 'この開催日が最新の掲載情報にありません。';
 if(r.e?.status==='cancelled')return '中止の掲載情報があります。';
 if(!r.sourceStart)return '開始時刻が未確認です。';
 if(!r.sourceEnd)return '終了時刻が未確認です。';
 if(r.e?.calendarBlocked)return '公表時刻に要確認の情報があります。主催者案内を確認してください。';
 return '自分の参加時間が公表時間の範囲に収まっていません。';
}
function issueAction(x){
 const entry=model.entries[x.key],e=EV.get(entry?.id),leg=x.type==='move'?findLeg(x.key):null;
 const title=leg?`${leg.from.venue?.name||'会場'} → ${leg.to.venue?.name||'会場'}`:e?.title||entry?.title||'移動区間';
 let action=`data-focus-plan="${esc(x.key)}"`,label='この予定を確認する';
 if(x.type==='move'){action=`data-edit-leg="${esc(x.key)}"`;label='移動時間を確認する';}
 else if(x.type==='changed'||x.type==='review'){action=`data-review="${esc(x.key)}"`;label='開催情報を確認する';}
 else if(x.type==='partial'||x.type==='conflict'){action=`data-edit-time="${esc(x.key)}"`;label='参加時間を調整する';}
 else if(x.type==='invalid'&&e){action=knownTime(e,entry.day)?`data-edit-time="${esc(x.key)}"`:`data-detail="${esc(e.id)}" data-day="${entry.day}"`;}
 return `<li><strong>${esc(title)}</strong><p>${esc(x.text)}</p><button ${action}>${label} →</button></li>`;
}
function issuesHTML(p){
 if(!p.issues.length)return '';
 return `<details class="plan-issues notice warn" id="plan-issues"><summary>確認が必要：${p.issues.length}件 — 確認箇所を見る</summary><p>カレンダー保存前に、次の項目を確認してください。</p><ul class="issue-list">${p.issues.map(issueAction).join('')}</ul></details>`;
}
function nextPlanHTML(p){
 const now=nowJST();if(demo||now.day!==p.day)return '';
 const active=p.ordered.find(r=>r.start<=now.minute&&now.minute<r.end),next=p.ordered.find(r=>r.start>now.minute),target=active||next;
 if(!target)return '<div class="plan-now notice">今日の参加予定は終了時刻を迎えました。</div>';
 const i=p.ordered.indexOf(target),leg=i>0?p.legs[i-1]:null,depart=leg?.minutes!=null?target.start-leg.minutes-leg.buffer:null;
 return `<section class="plan-now"><p>${active?'予定上の参加時間です':'次の予定'} · ${time(target.start)}–${time(target.end)}</p><h2>${esc(target.e.title)}</h2>${!active&&depart!==null?`<p>出発の目安 ${time(depart)}（直前の会場から）</p>`:''}<div>${link(directions(null,target.venue,leg?.mode||'walking'),'経路を確認 ↗','button secondary')}<button class="button secondary" data-focus-plan="${esc(target.key)}">この予定を見る</button></div></section>`;
}
function renderContextGF(rows){
 const box=$('#context-garraway');if(!box)return;
 const pick=rows.find(r=>r.e.venue==='garraway'&&knownTime(r.e,r.day)&&!['check','soldout','cancelled'].includes(r.e.status));
 box.hidden=!pick||filters.venue==='garraway';if(box.hidden)return;
 const start=min(slot(pick.e,pick.day)[0]),label=start<720?'出発前の交流に':start>=1080?'一日の最後のミートアップに':'予定の合間の交流に';
 box.innerHTML=`<div><small>GARRAWAY F / ${dayName(pick.day)}</small><h2>${label}</h2><p>${esc(pick.e.title)} · ${esc(slot(pick.e,pick.day).join('–'))}</p><p class="file-help">掲載企画の開催時間です。参加条件は詳細で確認できます。</p></div><button class="button secondary" data-detail="${esc(pick.e.id)}" data-day="${pick.day}">企画を見る ↗</button>`;
}
function planTable(p,forPrint=false){let rows=[];p.ordered.forEach((r,i)=>{rows.push(`<tr><td>${time(r.start)}<br>–${time(r.end)}</td><td><b>${r.number}.</b> ${forPrint?esc(r.e.title):`<button data-detail="${esc(r.e.id)}" data-day="${r.day}">${esc(r.e.title)}</button>`}<br><small>${esc(r.venue?.name||'会場要確認')}</small></td><td>${regLabel(r)}${r.changed?'<br>開催情報変更あり':''}${r.needsReview?'<br>要確認':''}${r.x.start||r.x.end?'<br>参加時間を調整済み':''}</td></tr>`);const l=p.legs[i];if(l){rows.push(`<tr class="move-row"><td>${time(l.depart)}<br>–${time(l.arrive)}</td><td>移動 ${l.minutes===null?'要確認':l.minutes+'分'}${l.manual?'（手入力）':'（目安）'}<br><small>${esc(l.from.venue?.name)} → ${esc(l.to.venue?.name)}</small></td><td>予備 ${l.buffer}分${l.free===null?'<br>所要時間未入力':l.free<0?'<br>'+(-l.free)+'分不足':''}</td></tr>`);if(l.arrive!==null&&l.buffer>0)rows.push(`<tr class="move-row"><td>${time(l.arrive)}<br>–${time(l.arrive+l.buffer)}</td><td>入館・受付の予備時間</td><td>${l.buffer}分</td></tr>`);const g=p.gaps.find(g=>g.key===l.key);if(g)rows.push(`<tr class="gap-row"><td>${time(g.start)}<br>–${time(g.end)}</td><td>空き時間</td><td>${g.minutes}分</td></tr>`);}});p.unresolved.forEach(r=>rows.push(`<tr><td>未確定</td><td>${esc(r.e?.title||r.x.title)}</td><td>時刻・開催条件を確認</td></tr>`));return `<table class="plan-table"><thead><tr><th>時刻</th><th>予定・会場</th><th>確認事項</th></tr></thead><tbody>${rows.join('')}</tbody></table>`;}
function renderPlan(){const days=daysInPlan();counts();if(!days.length){$('#plan-empty').innerHTML=empty('行きたい企画から、一日をつくろう。','イベントの「＋ 行く予定に入れる」で、この日の行程と会場マップができます。<br>♡気になるとは別に保存されます。',`<button class="button primary" data-screen="explore">イベントを探す</button><button class="button secondary" data-action="demo">地図付きの操作例を見る ↗</button>`);$('#plan-content').innerHTML='';return;}$('#plan-empty').innerHTML='';if(!days.includes(model.day))model.day=days[0];const p=itinerary(model.day);const items=planItems(p),stats=`<div class="plan-stats"><span>参加予定 <strong>${p.rows.length}</strong>件</span><span>確認が必要 <strong>${p.issues.length}</strong>件</span><span><strong>${new Set(p.ordered.map(r=>r.venue?.id)).size}</strong>会場</span><span><strong>${p.travel}</strong>分 移動${p.unknown?'＋未確認':''}</span></div>`;
 $('#plan-content').innerHTML=`<div class="plan-daybar"><div class="plan-dates" role="group" aria-label="予定を表示する日付">${days.map(day=>`<button class="plan-date" data-plan-day="${day}" aria-pressed="${model.day===day}">${dayName(day)}<span>${dayRows(day).length}件</span></button>`).join('')}</div>${stats}</div>${nextPlanHTML(p)}${issuesHTML(p)}<p class="plan-storage-note">マイ予定はこの端末・ブラウザに保存されます。予定の追加は参加申込ではありません。</p><div class="plan-layout"><div class="plan-flow"><div class="flow-head"><h2>${dayName(model.day)} の流れ</h2><div class="segmented" role="group" aria-label="予定表の表示形式"><button data-plan-view="timeline" aria-pressed="${model.view==='timeline'}">タイムライン</button><button data-plan-view="table" aria-pressed="${model.view==='table'}">一覧表</button></div></div>${model.view==='table'?`<div class="table-wrap">${planTable(p)}</div>`:p.ordered.map((r,i)=>planEventHTML(r)+(p.legs[i]?legHTML(p.legs[i])+(p.gaps.find(g=>g.key===p.legs[i].key)?gapHTML(p.gaps.find(g=>g.key===p.legs[i].key)):''):'')).join('')+(p.unresolved.length?'<h3 class="unresolved-title">確認してから組み込む予定</h3>'+p.unresolved.map(planEventHTML).join(''):'')}</div><aside class="plan-map-aside">${mapHTML('plan-map',items,'訪問順のマップ',`${new Set(items.filter(x=>geo(x.venue)).map(x=>x.venue.id)).size}会場 ／ 予定と地図を同じ番号で表示`)}<div class="plan-side-note"><h3>予定はこのブラウザに保存されます。</h3><p>PCとスマホの自動同期はありません。「保存・共有」から予定ファイルを渡すと、別の端末でも続けられます。</p><button class="text-button" data-action="export">この日の予定を保存・共有 ↗</button></div></aside></div>`;mountMap('plan-map',items);}
function focusPlan(key){const x=model.entries[key];if(!x)return;model.day=x.day;model.view='timeline';planFocus=key;closeModal();displayScreen('plan',{scroll:false});const el=document.getElementById('stop-'+key);el?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});mapViews.get('plan-map')?.selectKey(key);}
function renderToday(){const days=daysInPlan();if(!days.length){$('#today-content').innerHTML=empty('まずは、参加する日の予定を。','行きたいイベントを追加すると、その日の次の予定・会場・移動目安を確認できます。',`<button class="button primary" data-screen="explore">予定を探す</button><button class="button secondary" data-action="demo-today">当日ナビの操作例を見る</button>`);return;}
 const now=nowJST(),real=days.includes(now.day)&&!demo,day=real?now.day:(days.includes(model.day)?model.day:days[0]),p=itinerary(day),clock=real?now.minute:min(todayTestTime),active=p.ordered.find(r=>r.start<=clock&&clock<r.end),next=p.ordered.find(r=>r.start>clock),target=active||next,items=planItems(p);const nextIndex=target?p.ordered.findIndex(r=>r.key===target.key):-1,leg=nextIndex>0?p.legs[nextIndex-1]:null;
 let content='';if(target){const depart=leg&&leg.minutes!==null?target.start-leg.minutes-leg.buffer:null;content=`<div class="today-card"><p class="eyebrow">${active?'予定上の参加時間です':'NEXT EVENT'}</p><div class="today-time">${time(target.start)}<small> から</small></div><h2>${esc(target.e.title)}</h2><p><strong>${esc(target.venue?.name||'会場未確認')}</strong>${target.e.room?'<br>'+esc(target.e.room):''}</p>${!active&&depart!==null?`<p><b>${time(depart)}ごろの出発を推奨〈目安〉</b><br>直前の会場から移動${leg.minutes}分＋予備${leg.buffer}分で算出。</p>`:''}<p>${active?'開催中かどうかは主催者案内で確認してください。':nextIndex===0?'出発地からの移動は計算していません。現在地からの経路を地図で確認してください。':leg?.minutes===null?'移動時間が未確認です。マイ予定で入力してください。':'現在地は取得していません。実際にいる場所からの道順は地図で確認してください。'}</p><div class="today-actions">${link(directions(null,target.venue,leg?.mode||'walking'),'現在地からの経路 ↗','button dark')}<button class="button secondary" data-detail="${esc(target.e.id)}" data-day="${day}">主催者案内・参加条件</button><button class="button secondary" data-focus-plan="${esc(target.key)}">予定を調整</button></div></div>${active&&next?`<div class="today-summary"><h3>この後の予定 ${time(next.start)}–</h3><p>${esc(next.e.title)}<br>${esc(next.venue?.name)}</p><button class="text-button" data-focus-plan="${esc(next.key)}">移動と参加時間を確認 ↗</button></div>`:''}`;}else content=empty('この時間以降の予定はありません。','予定の終了を確認し、保存した候補や別の日程を見てみましょう。',`<button class="button primary" data-screen="plan">マイ予定に戻る</button>`);
 $('#today-content').innerHTML=`${!real?`<div class="today-banner"><b>${demo?'操作例':'会期当日ではないため'}：</b>${dayName(day)}の予定で、当日の画面を確認できます。現在開催中という表示ではありません。</div>`:''}<div class="clock-label">${real?'日本時間 '+dayName(now.day)+' '+now.clock:'確認する日：'+dayName(day)}${!real?`<label>仮の時刻<input id="today-test-time" type="time" value="${esc(todayTestTime)}" aria-label="当日画面を確認する仮の時刻"></label>`:''}</div>${issuesHTML(p)}<div class="today-layout"><div>${content}</div>${mapHTML('today-map',items,'今日の会場マップ','この日の参加予定に連動')}</div>`;const map=mountMap('today-map',items);if(target)map.selectKey(target.key);}
function visibleVenues(){let vs;if(mapScope==='plan'){vs=planItems(itinerary(model.day)).map(x=>x.venue).filter(Boolean);}else if(mapScope==='results'){const ids=new Set(occurrences().map(r=>r.e.venue));vs=D.venues.filter(v=>ids.has(v.id));}else vs=D.venues.filter(v=>!['tbd','private','city','kyushu-venues','v-9c4fea060c'].includes(v.id));return [...new Map(vs.map(v=>[v.id,v])).values()].filter(v=>mapArea==='all'||v.area===mapArea);}
function renderAllMap(){$('#map-scope').value=mapScope;$('#map-area').innerHTML='<option value="all">すべて</option>'+[...new Set(D.venues.map(v=>v.area))].sort().map(a=>`<option value="${esc(a)}">${esc(a)}</option>`).join('');$('#map-area').value=mapArea;const vs=visibleVenues(),items=mapScope==='plan'?planItems(itinerary(model.day)).filter(x=>vs.some(v=>v.id===x.venue?.id)):vs.map((v,i)=>({key:'venue-'+v.id,venue:v,number:i+1,title:v.name,start:null}));$('#allmap-content').innerHTML=`<div class="allmap-layout"><div>${mapHTML('all-map',items,mapScope==='plan'?dayName(model.day)+'のマイ予定':'会場マップ',`${vs.length}会場 ／ 位置確認済み ${vs.filter(v=>geo(v)).length}会場`,mapScope==='plan')}</div><div class="venue-list">${vs.map(v=>`<article class="venue-row"><span class="badge ${geo(v)?'blue':'warn'}">${geo(v)?esc(v.area):'位置未確認'}</span><h3>${esc(v.name)}</h3><p>${esc(v.geo?.address||v.note||'詳しい場所・利用条件は主催者案内で確認してください。')}</p><div class="venue-actions"><button data-search-venue="${esc(v.id)}">この会場の予定を見る</button>${link(placeLink(v),'地図で確認 ↗')}</div></article>`).join('')||'<div class="empty-state"><h3>対象の会場がありません</h3><p>日付や表示条件を変更してください。</p></div>'}</div></div>`;mountMap('all-map',items,mapScope==='plan');}
function renderGF(){const own=D.events.filter(e=>e.venue==='garraway'&&e.origin==='主催者予定');$('#gf-events').innerHTML=[7,8,9].map(n=>{const day='2026-10-0'+n;return `<h2 class="gf-day-title">${dayName(day)}</h2>`+own.filter(e=>e.dates.includes(day)).sort((a,b)=>(slot(a,day)[0]||'').localeCompare(slot(b,day)[0]||'')).map(e=>cardHTML(e,day)).join('');}).join('');$('[data-gf-map]').href=placeLink(VEN.get('garraway'));}
function openModal(type,title,html){modalType=type;$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;const dlg=$('#modal');if(!dlg.open)dlg.showModal();$('#modal-body').scrollTop=0;requestAnimationFrame(()=>dlg.querySelector('.close-dialog')?.focus({preventScroll:true}));}
function closeModal(){if($('#modal').open)$('#modal').close();modalType='';}
function selectedOption(value,current){return String(value)===String(current)?' selected':'';}
function options(values,current){return values.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}"${selectedOption(v,current)}>${esc(t)}</option>`;}).join('');}
function openFilters(){openModal('filters','イベントを絞り込む',`<p class="modal-intro">条件を選んで、必要なイベントだけに。無料でも申込が必要な場合があります。</p><form id="filter-form"><div class="field-grid"><label class="field"><span>会場</span><select name="venue">${options([['all','すべての会場'],...D.venues.map(v=>[v.id,v.name])],filters.venue)}</select></label><label class="field"><span>テーマ</span><select name="category">${options([['all','すべてのテーマ'],...[...new Set(D.events.map(e=>e.category))].sort()],filters.category)}</select></label><label class="field"><span>エリア</span><select name="area">${options([['all','すべてのエリア'],...[...new Set(D.venues.map(v=>v.area))].sort()],filters.area)}</select></label><label class="field"><span>時間帯（重なる予定も表示）</span><select name="period">${options([['all','すべて'],['morning','午前（12時まで）'],['afternoon','午後（12〜18時）'],['evening','夕方から（18時以降）'],['unknown','時刻未確定']],filters.period)}</select></label><label class="field"><span>参加費・申込条件</span><select name="fee">${options([['all','すべて'],['free','無料と明記'],['no-registration','無料・予約不要と明記']],filters.fee)}</select></label><label class="field"><span>イベントとセッション</span><select name="kind">${options([['grouped','関係をまとめて表示'],['events','イベント全体だけ'],['sessions','個別セッションだけ'],['all','すべて独立して表示']],filters.kind)}</select></label><label class="field"><span>この時刻以降に開始</span><input name="from" type="time" value="${esc(filters.from)}"></label><label class="field"><span>この時刻までに終了</span><input name="until" type="time" value="${esc(filters.until)}"></label></div><p class="file-help">時刻指定は、その時間内に全体が収まる予定を表示します。未公表・不一致の時刻は除外します。</p><label class="check-field"><input type="checkbox" name="known" ${filters.known?'checked':''}>時刻が確認できる予定だけ</label><label class="check-field"><input type="checkbox" name="candidates" ${filters.candidates?'checked':''}>♡ 気になるに保存したものだけ</label><div id="form-error" class="form-error" hidden role="alert"></div><div class="form-actions"><button type="button" class="button secondary" data-action="reset-filters-modal">条件を解除</button><button type="submit" class="button primary">この条件で表示</button></div></form>`);}
function detail(id,day){const e=EV.get(id);if(!e)return;if(!e.dates.includes(day))day=e.dates[0];pending={type:'detail',id,day};const [a,b]=slot(e,day),v=VEN.get(e.venue),x=model.entries[k(id,day)],saved=model.candidates.includes(id),safe=knownTime(e,day)&&(!['check','soldout'].includes(e.status)||x?.reviewed===signature(e,day)),sourceDate=e.autoCheckedAt||e.checkedAt||D.meta.fetchedAt;const parent=e.parent&&EV.get(e.parent),cs=(children.get(id)||[]).filter(c=>c.dates.includes(day));
 openModal('detail','イベントの詳細',`<div class="badges">${e.category?'<span class="badge blue">'+esc(e.category)+'</span>':''}${statusBadges(e,day)}</div><h3 class="detail-title">${esc(e.title)}</h3>${e.dates.length>1?`<label class="field"><span>参加する日を選ぶ</span><select id="detail-date" data-id="${esc(id)}">${options(e.dates.map(d=>[d,dayName(d)]),day)}</select></label>`:`<p class="event-date">${dayName(day)}</p>`}<p class="detail-clock">${esc(a||'時刻未公表')}${b?'–'+esc(b):''}</p><p class="detail-place">${esc(v?.name||'会場要確認')}</p><p class="subtle">${esc(e.room||'')} ${v?.geo?.address?'<br>'+esc(v.geo.address):''}</p><div class="badges">${feeBadge(e)}<span class="badge">${isFlexible(e)?'入退場自由の記載あり':'途中入退場は要確認'}</span></div>${e.speaker?`<p class="detail-description"><b>登壇者</b><br>${esc(e.speaker)}</p>`:''}${e.description?`<p class="detail-description">${esc(e.description)}</p>`:''}<div class="detail-notes">${(e.notes||[]).map(n=>'<p>'+esc(n)+'</p>').join('')}</div>${parent?`<p class="manual-note">このセッションは「${esc(parent.title)}」の一部です。<button class="text-button" data-detail="${esc(parent.id)}" data-day="${day}">イベント全体を見る</button></p>`:''}${cs.length?'<div class="help-section"><h3>この日の個別セッション</h3>'+cs.map(c=>`<button class="text-button" style="display:block;text-align:left" data-detail="${esc(c.id)}" data-day="${day}">${esc(slot(c,day).filter(Boolean).join('–'))} ${esc(c.title)} ↗</button>`).join('')+'</div>':''}<div class="detail-actions"><button class="button secondary" data-candidate="${esc(id)}" aria-pressed="${saved}">${saved?'♥ 気になるに保存済み':'♡ 気になるに保存'}</button><button class="button primary" data-add="${esc(id)}" data-day="${day}" aria-pressed="${!!x}">${x?'✓ 行く予定に追加済み':'＋ 行く予定に入れる'}</button></div><p class="file-help">「気になる」とマイ予定は別です。どちらも参加予約ではありません。この端末・ブラウザに保存されます。</p><div class="detail-actions">${url(e.url)?link(e.url,'主催者サイトで申し込む ↗','button dark'):'<span class="manual-note">Garraway F独自企画。参加条件は上記の主催者予定をご確認ください。</span>'}${link(placeLink(v),'会場・経路 ↗','button secondary')}</div>${x?`<button class="button secondary" data-registration="${esc(k(id,day))}">${regLabel({x,e})} → 記録</button>`:''}<div class="detail-actions"><button class="button secondary" data-google-event="${esc(id)}" data-day="${day}" ${safe?'':'disabled'}>Googleカレンダーへ ↗</button><button class="button secondary" data-ics-event="${esc(id)}" data-day="${day}" ${safe?'':'disabled'}>この枠を .ics 保存</button></div>${!safe?'<p class="file-help">時刻が未確定・不一致、または開催条件が要確認です。マイ予定に保存して内容を確認してから書き出してください。中止・未確定時刻は書き出せません。</p>':''}<div class="detail-source"><b>掲載情報の出典</b><br>${url(e.source)?link(e.source,esc(e.source)):esc(e.source||e.origin||'掲載データ')}<br>確認時点：${esc(sourceDate)}<br>主催者による更新がこの保存データに反映されていない場合があります。出発前に最新の主催者案内を確認してください。</div>`);
}
function findLeg(key){for(const day of daysInPlan()){const l=itinerary(day).legs.find(l=>l.key===key);if(l)return l;}return null;}
function editLeg(key){const l=findLeg(key);if(!l){toast('移動区間が変わりました。最新の予定表をご確認ください。');return;}pending={type:'leg',key};openModal('leg','移動方法・所要時間を変更',`<p class="modal-intro"><strong>${esc(l.from.venue?.name||'会場未確認')}</strong><br>↓<br><strong>${esc(l.to.venue?.name||'会場未確認')}</strong></p><form id="leg-form" data-key="${esc(key)}"><label class="field"><span>移動方法</span><select name="mode" id="leg-mode">${options([['walking','徒歩'],['transit','公共交通'],['driving','車・タクシー']],l.mode)}</select></label><label class="field"><span>確認した所要時間（分）</span><input name="minutes" id="leg-minutes" type="number" inputmode="numeric" min="0" max="720" step="1" value="${l.manual?l.minutes:''}" placeholder="地図で確認した分数を入力"><small>徒歩は空欄で目安を自動計算。公共交通と車・タクシーは入力が必要です。</small></label>${link(l.url,'Googleマップで経路・時間を確認 ↗','button secondary')}<p class="file-help">地図側で利用日・出発時刻を設定し、待ち時間・乗り換えも含めて入力してください。予備時間${model.settings.buffer}分は別に加算します。</p><div class="notice">現在の算定：${esc(l.method)}${l.minutes!==null?' ／ '+l.minutes+'分':''}<br>同じ会場は移動0分。別会場の徒歩目安は直線距離×1.35を歩行速度で割り、5分単位に切り上げます。</div><div id="form-error" class="form-error" hidden role="alert"></div><div class="form-actions"><button type="button" class="button secondary" data-action="reset-leg">徒歩の自動計算に戻す</button><button type="submit" class="button primary">この移動に反映</button></div></form>`);}
function editTime(key){const r=dayRows(model.entries[key]?.day).find(r=>r.key===key);if(!r||!r.e||!knownTime(r.e,r.day)){toast('公表時刻が未確定のため、参加時間を調整できません。');return;}pending={type:'time',key};openModal('time','自分が参加する時間を調整',`<p class="modal-intro"><strong>${esc(r.e.title)}</strong><br>${dayName(r.day)} ／ 開催時間 ${esc(r.sourceStart)}–${esc(r.sourceEnd)}</p><form id="visit-form" data-key="${esc(key)}"><div class="field-grid"><label class="field"><span>参加開始</span><input type="time" name="start" value="${esc(r.x.start||r.sourceStart)}" required></label><label class="field"><span>参加終了</span><input type="time" name="end" value="${esc(r.x.end||r.sourceEnd)}" required></label></div>${isFlexible(r.e)?'<div class="notice">主催者予定に「入退場自由」の記載があります。</div>':'<label class="check-field"><input type="checkbox" name="partial" '+(r.x.partialConfirmed?'checked':'')+'>主催者案内で途中入退場が可能と確認した</label><p class="file-help">時間を変更できることと、途中入退場できることは別です。講演・セッションを途中で切る場合は確認が必要です。</p>'}<div id="form-error" class="form-error" hidden role="alert"></div><div class="form-actions"><button type="button" class="button secondary" data-reset-time="${esc(key)}">開催時間に戻す</button><button type="submit" class="button primary">参加時間を反映</button></div></form>`);}
function registration(key){const x=model.entries[key],e=EV.get(x?.id);if(!x)return;pending={type:'registration',key};openModal('registration','申込状況を記録する',`<p class="modal-intro"><strong>${esc(e?.title||x.title)}</strong><br>${dayName(x.day)}<br>これは自分用の記録です。主催者への申し込みは行われません。</p>${url(e?.url)?link(e.url,'主催者サイトで申し込む ↗','button dark'):''}<form id="registration-form" data-key="${esc(key)}" style="margin-top:20px"><label class="field"><span>現在の状態（自己申告）</span><select name="registration">${options([['unknown','まだ確認していない'],['pending','申込が必要・まだ申し込んでいない'],['done','申し込みを完了した'],['notrequired','申込不要と確認した']],x.registration)}</select></label><p class="file-help">申込ページを開いただけでは「申込済み」になりません。完了メールなどをご自身で確認して記録してください。</p><div class="form-actions"><button class="button primary" type="submit">この日の記録を保存</button></div></form>`);}
function review(key){const x=model.entries[key],e=EV.get(x?.id);if(!x||!e){toast('現在のデータに予定がありません。主催者の案内をご確認ください。');return;}const r=dayRows(x.day).find(r=>r.key===key);let old=null;try{old=JSON.parse(x.snapshot);}catch{}pending={type:'review',key};openModal('review','開催情報と変更内容を確認',`<h3>${esc(e.title)}</h3>${r.changed?`<div class="review-change"><div><small>保存したとき</small>${esc(old?.[0]||x.title)}<br>${esc(old?.[3]||x.day)} ${esc(old?.[4]||'未確認')}–${esc(old?.[5]||'未確認')}<br>${esc(VEN.get(old?.[1])?.name||x.venue)}<br>${esc(old?.[8]||'')}</div><div><small>今回の掲載データ</small>${esc(e.title)}<br>${esc(x.day)} ${esc(slot(e,x.day)[0]||'未確認')}–${esc(slot(e,x.day)[1]||'未確認')}<br>${esc(VEN.get(e.venue)?.name)}<br>${esc(e.fee||'')}</div></div>`:''}<div class="detail-notes">${(e.notes||[]).map(n=>'<p>'+esc(n)+'</p>').join('')}</div>${e.status==='soldout'?'<div class="notice warn">完売表記があります。参加可否を主催者に確認してください。</div>':''}${link(e.url||url(e.source),'主催者の最新案内を確認 ↗','button dark')}<p class="file-help">この画面は${esc(D.meta.fetchedAt||D.meta.checkedAt)}時点の保存データです。未確定の時刻・中止の予定は、確認を記録しても書き出せません。</p><form id="review-form" data-key="${esc(key)}"><label class="check-field"><input type="checkbox" name="read" required>変更内容・主催者の開催条件を確認しました</label><div class="form-actions">${knownTime(e,x.day)&&r.invalid?`<button type="button" class="button secondary" data-reset-time="${esc(key)}">参加時間を公表時間に戻す</button>`:''}<button type="submit" class="button primary">確認したことを記録</button></div></form>`);}
function openSettings(){openModal('settings','移動と保存の設定',`<form id="settings-form"><div class="field-grid"><label class="field"><span>会場到着後の予備時間</span><select name="buffer">${options([0,5,10,15,20,30].map(x=>[x,x+'分']),model.settings.buffer)}</select></label><label class="field"><span>徒歩の計算速度</span><select name="speed">${options([[50,'ゆっくり（50m/分）'],[70,'標準（70m/分）'],[90,'速め（90m/分）']],model.settings.speed)}</select></label></div><div class="notice">同じ会場は移動0分、別フロアなど同じ建物付近は目安5分。予備時間は別に加算します。徒歩は実際の道順、信号、階段、入口を考慮した経路計算ではありません。移動条件に合わせて区間ごとに調整してください。</div><div class="form-actions"><button type="submit" class="button primary">予定表に反映</button></div></form><div class="help-section"><h3>別の端末に予定を渡す</h3><p>このブラウザに保存します。アカウント登録や自動同期はありません。予定ファイルを書き出し、別端末で読み込むと移動設定も引き継げます。</p><div class="detail-actions"><button class="button secondary" data-action="backup">予定ファイルを書き出す</button><button class="button secondary" data-action="import">予定ファイルを読み込む</button></div></div><div class="help-section"><h3>旧版の保存データ</h3><p>同じブラウザ内の旧版データを、明示的に読み込めます。旧版のデータは削除・変更しません。候補から予定を自動生成することもありません。</p><button class="button secondary" data-action="import-legacy">旧版の保存を読み込む</button></div>`);}
function formError(text){const el=$('#form-error');if(el){el.textContent=text;el.hidden=false;el.scrollIntoView({block:'nearest'});}else toast(text);}
function suggestGap(key){const g=daysInPlan().flatMap(d=>itinerary(d).gaps).find(g=>g.key===key);if(!g){toast('予定が変わりました。最新の空き時間をご確認ください。');return;}let picks=[];for(const e of D.events){if(!e.dates.includes(g.from.day)||!knownTime(e,g.from.day)||['check','soldout','cancelled'].includes(e.status)||model.entries[k(e.id,g.from.day)]||relationEntries(e.id,g.from.day).length)continue;const v=VEN.get(e.venue),go=estimate(g.from.venue,v),back=estimate(v,g.to.venue);if(go.minutes===null||back.minutes===null)continue;const [a,b]=slot(e,g.from.day).map(min),start=Math.max(a,g.from.end+go.minutes+model.settings.buffer),end=Math.min(b,g.to.start-back.minutes-model.settings.buffer);if(end-start<20)continue;if(!isFlexible(e)&&(start!==a||end!==b))continue;if(start<g.start||end>g.end)continue;picks.push({e,start,end,go:go.minutes,back:back.minutes});}
 picks.sort((a,b)=>(a.go+a.back)-(b.go+b.back)||a.start-b.start);pending={type:'gap',day:g.from.day,picks:picks.slice(0,8)};openModal('gap','空き時間に立ち寄れる企画',`<p class="modal-intro">${dayName(g.from.day)} ${time(g.start)}–${time(g.end)} の空き時間。前後の会場への徒歩目安と予備時間を含めて、時間上収まる候補です。</p><div class="notice warn">満席・申込状況は確認していません。利用できることを保証するおすすめではありません。入退場自由と明記された企画だけ、部分参加を候補に含めます。</div>${picks.length?picks.slice(0,8).map((p,i)=>`<article class="recommend-card"><span class="badge blue">前後の移動 計${p.go+p.back}分の目安</span><h3>${esc(p.e.title)}</h3><p>${esc(VEN.get(p.e.venue)?.name)} ／ ${time(p.start)}–${time(p.end)} の参加<br>${esc(p.e.fee)}</p><button class="button primary" data-add-suggestion="${i}">この時間で予定に追加</button><button class="text-button" data-detail="${esc(p.e.id)}" data-day="${g.from.day}">参加条件を見る</button></article>`).join(''):empty('条件を満たす企画は見つかりませんでした。','この時間は休憩・食事のために空けておくか、検索で他の候補をご確認ください。','<button class="button secondary" data-action="close-modal">予定表に戻る</button>')}`);}
function openHelp(){openModal('help','使い方・データと保存について',`<div class="help-steps"><div class="help-step"><div><h3>参加する日から探す</h3><p>会場・テーマ・料金・時間帯で絞り込めます。複数の検索語はスペースで区切ります。英字の大小、全半角、ひらがな・カタカナは区別しません。</p></div></div><div class="help-step"><div><h3>♡は気になる。＋は、この日の予定。</h3><p>候補と参加予定は別々です。複数日イベントでも追加した日だけが予定になります。参加の申し込みは主催者案内から行ってください。</p></div></div><div class="help-step"><div><h3>地図と移動を見て一日を組む</h3><p>マイ予定と地図は同じ番号で対応します。同じ会場に戻る場合は「1・4」のように表示。移動と予備時間、空き時間も確認できます。</p></div></div><div class="help-step"><div><h3>保存して、当日は次の会場へ</h3><p>保存の対象を「この日／全日程」から選べます。当日ナビは選んだ予定を案内します。現在地を勝手に取得したり、申込を自動実行したりはしません。</p></div></div></div><div class="help-section"><h3>このガイドについて</h3><p>${CFG.preview?'公開前の独立したプレビューです。公開サイトと既存の保存済み予定は変更していません。操作例は別の保存領域を使い、実際の予約ではありません。':'Garraway Fが編集する非公式回遊ガイドです。'}</p><p>データ取得時点：${esc(D.meta.fetchedAt||D.meta.checkedAt)}。${D.events.filter(e=>e.kind==='event').length}イベント・${D.events.filter(e=>e.kind==='session').length}個別セッションを保存しています。複数日開催は日別の枠として表示します。</p><p>登録先と時間割で不一致・未公表の情報があります。公表されていないイベントもあり、完全網羅・リアルタイム更新を保証しません。このプレビューは保存データを使い、自動取得処理を実行しません。</p></div><div class="help-section"><h3>移動と地図の見方</h3><p>位置図は掲載会場の座標によるものです。実際の道路を描いたものではありません。破線は訪問順。入口・バリアフリー経路・信号・交通状況を考慮した経路ではありません。</p><p>徒歩目安は、直線距離×1.35÷歩行速度を5分単位で切り上げます。同じ会場0分、同じ建物付近5分、5kmを超える区間・位置未確認の会場は自動算定しません。</p><p>道路地図と外部経路には通信が必要です。ローカルHTMLでは道路地図を別タブで開きます。Web上ではOpenStreetMapの地図画像を利用でき、外部サービスへの通信が発生します。地図提供元の利用条件に従います。</p></div><div class="help-section"><h3>端末保存・カレンダー</h3><p>ログインなしでこのブラウザに保存します。別ブラウザ・別端末には自動同期されません。閲覧データを削除すると消えるため「予定ファイル」のバックアップをご利用ください。</p><p>プライベートブラウズやアプリ内ビューアでは保存・HTML操作・ダウンロードに制約がある場合があります。通常のブラウザでの確認を推奨します。</p><p>カレンダーファイルは一時点のコピーです。主催者の変更は自動同期されません。再取り込み時の重複処理はカレンダーアプリに依存します。主催者の最新案内を前日・当日に確認してください。</p></div><div class="help-section"><h3>出典</h3>${(D.meta.sources||[]).map(u=>'<p>'+link(u,esc(u))+'</p>').join('')}<p>Garraway F独自企画は主催者予定として区別しています。</p></div><div class="detail-actions"><button class="button primary" data-action="demo">操作例で試す</button><button class="button secondary" data-action="settings">保存の設定</button></div>`);}
// Calendar exports always state scope before writing. Unknown transfers block itinerary ICS, not backup/print/text.
function stamp(day,n){const d=new Date(day+'T00:00:00+09:00');d.setTime(d.getTime()+n*60000);return d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');}
const icsEscape=s=>String(s??'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function fold(s){let lines=[],part='',bytes=0;for(const c of s){const n=new TextEncoder().encode(c).length;if(bytes+n>73){lines.push(part);part=' ';bytes=1;}part+=c;bytes+=n;}lines.push(part);return lines.join('\r\n');}
function calendarRows(p){const out=p.ordered.map(r=>({uid:r.key,title:r.e.title,start:r.start,end:r.end,day:r.day,location:venueLocation(r.venue),description:'自分の参加予定。予約ではありません。主催者開催時間 '+r.sourceStart+'–'+r.sourceEnd+'。開催情報の変更は自動同期されません。',url:ROOT+'?date=any&event='+encodeURIComponent(r.e.id)+'&on='+r.day}));for(const l of p.legs){if(l.minutes!==null&&l.depart!==null&&l.minutes>0)out.push({uid:'move-'+l.key,title:`【${l.manual?'手入力':'目安'}】${l.from.venue?.name} → ${l.to.venue?.name}`,start:l.depart,end:l.arrive,day:p.day,location:venueLocation(l.to.venue),description:l.method+'。実際の経路・到着時刻を保証しません。',url:l.url});if(l.arrive!==null&&l.buffer>0)out.push({uid:'buffer-'+l.key,title:'【予備時間】'+l.to.venue?.name,start:l.arrive,end:l.arrive+l.buffer,day:p.day,location:venueLocation(l.to.venue),description:'移動後の入館・受付の予備時間。移動0分の同じ会場でも別途確保。',url:ROOT});}return out.sort((a,b)=>a.start-b.start);}
function createICS(rows){const now=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Garraway F//RAMEN Guide V3//JA','CALSCALE:GREGORIAN','METHOD:PUBLISH'];for(const r of rows)lines.push('BEGIN:VEVENT','UID:'+icsEscape(r.uid)+'@ramen-guide.garrawayf.github.io','DTSTAMP:'+now,'DTSTART:'+stamp(r.day,r.start),'DTEND:'+stamp(r.day,r.end),'SUMMARY:'+icsEscape(r.title),'LOCATION:'+icsEscape(r.location),'DESCRIPTION:'+icsEscape(r.description),'URL:'+r.url,'STATUS:TENTATIVE','END:VEVENT');lines.push('END:VCALENDAR');return lines.map(fold).join('\r\n')+'\r\n';}
function download(name,content,mime){const blob=new Blob([content],{type:mime}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),15000);}
function exportDays(){return exportScope==='all'?daysInPlan():daysInPlan().includes(model.day)?[model.day]:[];}
function exportSummary(){const ds=exportDays(),ps=ds.map(itinerary),issues=ps.reduce((n,p)=>n+p.issues.length,0),events=ps.reduce((n,p)=>n+p.rows.length,0),legs=ps.reduce((n,p)=>n+p.legs.length,0);return {ds,ps,issues,events,legs};}
function openExport(){const days=daysInPlan();if(!days.length){toast('まずイベントをマイ予定に追加してください。');return;}if(!days.includes(model.day))model.day=days[0];openModal('export','予定を保存・共有',`<p class="modal-intro">保存する対象を明確にしてから書き出します。予定ファイルは、このブラウザと別の端末の間で受け渡しできます。</p><label class="field"><span>対象の日程</span><select id="export-scope">${options([['day',dayName(model.day)+'だけ'],['all','全日程（'+days.length+'日分）']],exportScope)}</select></label><div id="export-summary" class="export-summary"></div><div class="export-actions"><button class="button primary" data-action="export-ics">移動込みカレンダー .ics <span>↓</span></button><button class="button secondary" data-action="copy-plan">この範囲をテキスト共有 <span>↗</span></button><button class="button secondary" data-action="print-plan">この範囲の予定表を印刷 <span>↗</span></button><button class="button secondary" data-action="backup">全予定のバックアップ .json <span>↓</span></button></div><div id="export-error" class="notice warn" hidden></div><p class="file-help">.icsは自分の予定と移動のコピーです。参加予約・情報の自動同期ではありません。JSONは候補・全日程・申込メモ・移動設定を含むバックアップです。</p><div class="help-section"><h3>別端末へ引き継ぐ</h3><p>全予定のバックアップを別端末へ送り、この画面から読み込んでください。既存データの扱いを確認してから反映します。</p><button class="button secondary" data-action="import">予定ファイルを読み込む</button></div>`);updateExportSummary();}
function updateExportSummary(){
 const s=exportSummary();$('#export-summary').innerHTML=`<strong>${s.ds.map(d=>dayName(d)).join('・')}</strong><br>参加予定 ${s.events}件 ／ 移動 ${s.legs}区間${s.issues?`<div class="export-checks"><h3>保存前に、${s.issues}件確認してください</h3><ul class="issue-list">${s.ps.flatMap(p=>p.issues).map(issueAction).join('')}</ul></div>`:''}`;
 const b=$('[data-action="export-ics"]');if(b)b.textContent=(exportScope==='all'?'全日程':dayName(model.day))+'をカレンダー保存';
}
function exportICS(){const s=exportSummary();if(s.issues){const er=$('#export-error');if(er){er.hidden=false;er.innerHTML='上の確認項目から、該当する予定・移動を確認できます。テキスト・印刷・バックアップは注意事項付きで保存できます。';$('#export-summary').scrollIntoView({block:'start'});}toast('確認が必要な予定があります。該当箇所を直してから保存してください。');return false;}download('ramen-plan-'+(exportScope==='all'?'all-days':model.day)+'.ics',createICS(s.ps.flatMap(calendarRows)),'text/calendar;charset=utf-8');toast(s.ds.length+'日分のイベント・移動・予備時間を書き出しました。');return true;}
function shareText(days){const lines=['RAMEN TECH 2026 非公式回遊ガイド｜Garraway F','自分の参加予定（参加予約ではありません）'];if(demo)lines.push('【操作例】実在の企画を使った仮の参加計画です。');for(const day of days){const p=itinerary(day);lines.push('',dayName(day));if(p.issues.length)lines.push('【要確認】'+[...new Set(p.issues.map(x=>x.text))].join(' / '));for(let i=0;i<p.ordered.length;i++){const r=p.ordered[i];lines.push(`${r.number}. ${time(r.start)}–${time(r.end)} ${r.e.title}`,`   ${r.venue?.name||'会場確認'} ／ ${regLabel(r)}`);const l=p.legs[i];if(l){lines.push(`   移動 ${l.minutes===null?'未確認':l.minutes+'分'}（${l.method}）＋予備 ${l.buffer}分`);const g=p.gaps.find(g=>g.key===l.key);if(g)lines.push(`   空き ${time(g.start)}–${time(g.end)}（${g.minutes}分）`);}}for(const r of p.unresolved)lines.push('時刻・開催情報未確認：'+(r.e?.title||r.x.title));}lines.push('','移動は目安です。開催・申込条件と実際の経路は出発前に主催者・地図で確認してください。','掲載データ取得時点：'+D.meta.fetchedAt,ROOT);return lines.join('\n');}
async function copyPlan(){const text=shareText(exportDays());try{await navigator.clipboard.writeText(text);toast('選択した日程の予定をコピーしました。');}catch{openModal('copy','予定をコピー',`<p class="modal-intro">コピーできないブラウザでは、下の文章を選択してコピーするか、テキストファイルに保存してください。</p><textarea class="share-text" id="copy-text" readonly>${esc(text)}</textarea><div class="form-actions"><button class="button primary" data-action="download-text">テキストファイルを保存</button></div>`);$('#copy-text').focus();$('#copy-text').select();}}
function backup(){download('ramen-guide-backup-'+(demo?'sample-':'')+nowJST().day+'.json',JSON.stringify({...model,exportedAt:new Date().toISOString(),sample:demo,source:'RAMEN TECH guide v3'},null,2),'application/json;charset=utf-8');toast('候補・全日程・移動設定を予定ファイルに保存しました。');}
function importFile(){openModal('import','予定ファイルを読み込む',`<p class="modal-intro">このガイドで書き出した .json ファイルを選んでください。読み込み内容と、既存の予定の扱いを確認してから反映します。</p><label class="field"><span>バックアップファイル（最大2MB）</span><input id="import-file" type="file" accept="application/json,.json"></label><div id="form-error" class="form-error" hidden role="alert"></div>`);}
function importConfirm(m,sample=false){pending={type:'import',model:m};openModal('import-confirm','読み込み内容を確認',`<div class="export-summary">候補 ${m.candidates.length}件 ／ 参加予定 ${Object.keys(m.entries).length}件<br>${[...new Set(Object.values(m.entries).map(x=>x.day))].map(d=>dayName(d)).join('・')||'参加予定なし'}${sample?'<br><b>操作例として書き出されたデータです。</b>':''}</div><p class="modal-intro">追加の場合、同じ日・同じイベントが既にあれば、現在の予定を優先します。元のバックアップや旧版のデータは書き換えません。</p><div class="merge-choice"><button class="button primary" data-action="merge-import">今の予定に追加する（既存を優先）</button><button class="button secondary" data-action="replace-import-confirm">今の予定を置き換える…</button><button class="button secondary" data-action="close-modal">読み込まない</button></div>`);}
function importLegacy(){try{const raw=JSON.parse(localStorage.getItem('ramen-itinerary-v1')||'null'),oldCandidates=JSON.parse(localStorage.getItem('garrawayf-ramen-city-2026-favorites-v2')||'[]');if(!raw&&!oldCandidates?.length){toast('このブラウザには旧版の保存データがありません。別ドメイン・別端末の保存は読み込めません。');return;}const m=newModel();m.candidates=Array.isArray(oldCandidates)?oldCandidates.filter(x=>EV.has(x)):[];for(const [key,x] of Object.entries(raw?.entries||{})){const e=EV.get(x.id);if(!e||!e.dates.includes(x.day)||key!==k(x.id,x.day))continue;m.entries[key]={...makeEntry(e,x.day),start:x.start||'',end:x.end||'',snapshot:x.snapshot||signature(e,x.day),partialConfirmed:false};}m.settings.buffer=[0,5,10,15,20,30].includes(raw?.buffer)?raw.buffer:10;m.settings.speed=[50,70,90].includes(raw?.speed)?raw.speed:70;m.day=raw?.day||initialDay;/* Old hand-entered legs are deliberately not trusted: source signature format changed. */importConfirm(hydrate(m));}catch{toast('旧版の保存を読み取れませんでした。元データは変更していません。');}}
function eventRow(id,day){const e=EV.get(id);if(!e||!e.dates.includes(day)||!knownTime(e,day))return null;const x=model.entries[k(id,day)];if(['check','soldout'].includes(e.status)&&x?.reviewed!==signature(e,day))return null;if(x){const r=dayRows(day).find(r=>r.key===k(id,day));if(r.invalid||r.changed||r.needsReview||r.needsPartialReview)return null;return calendarRows({...itinerary(day),ordered:[r],legs:[]})[0];}const [s,t]=slot(e,day).map(min);return {uid:k(id,day),day,start:s,end:t,title:e.title,location:venueLocation(VEN.get(e.venue)),description:'参加予定。予約ではありません。主催者の変更は自動同期されません。',url:ROOT+'?event='+encodeURIComponent(id)+'&on='+day+'&date=any'};}
function googleEvent(id,day){const r=eventRow(id,day);if(!r){toast('時刻または開催条件の確認が必要です。');return;}const u=new URL('https://calendar.google.com/calendar/render');u.search=new URLSearchParams({action:'TEMPLATE',text:r.title,dates:stamp(r.day,r.start)+'/'+stamp(r.day,r.end),details:r.description+'\n'+r.url,location:r.location,ctz:'Asia/Tokyo'});window.open(u.href,'_blank','noopener,noreferrer');}
function printPlan(){const days=exportDays(),root=$('#print-root');closeModal();root.innerHTML=days.map(day=>{const p=itinerary(day);return `<section class="print-day"><p>RAMEN TECH 2026 非公式回遊ガイド｜Garraway F${demo?' ／ 操作例':''}</p><h1>${dayName(day)} マイ予定</h1><p>${p.rows.length}予定 ／ 移動${p.travel}分${p.unknown?'＋未確認':''} ／ 候補や検索結果はこの印刷に含みません。</p>${p.issues.length?'<div class="print-note">要確認：'+[...new Set(p.issues.map(x=>esc(x.text)))].join(' ／ ')+'</div>':''}<div class="print-map">${mapHTML('print-map-'+day,planItems(p),'会場の位置と訪問順','破線は実際の歩行経路ではありません。')}</div>${planTable(p,true)}<p class="print-disclaimer">この予定は参加予約ではありません。移動は目安で、実際の経路・到着を保証しません。申込状況は自己申告です。主催者の変更は自動反映されません。掲載情報取得時点：${esc(D.meta.fetchedAt)}。</p></section>`;}).join('');root.style.cssText='display:block;position:absolute;left:-2000px;width:730px;';root.setAttribute('aria-hidden','false');for(const day of days){const node=document.getElementById('print-map-'+day);node.querySelector('.map-heading').remove();node.querySelector('.map-status').style.display='none';node.querySelector('.map-legend').remove();node.querySelector('.map-route-list')?.remove();mountMap('print-map-'+day,planItems(itinerary(day)));}root.style.cssText='';requestAnimationFrame(()=>window.print());}
function startDemo(next='plan'){closeModal();if(!demo){userModel=model;demo=true;const loaded=load(DEMO_KEY);if(Object.keys(loaded.entries).length)model=loaded;else{model=newModel();model.day='2026-10-08';const examples=[['coffee-8','10:00','11:00'],['slot-32c206f2-e7b1-409b-bf1f-f7cb8fda1012','',''],['event-cross-border-open-innovation-day','',''],['connect-8','18:30','19:30']];for(const [id,start,end] of examples){const e=EV.get(id);if(e&&e.dates.includes(model.day)){const x=makeEntry(e,model.day);x.start=start;x.end=end;x.partialConfirmed=isFlexible(e);model.entries[k(id,model.day)]=x;}}model.candidates=['coffee-8','event-cross-border-open-innovation-day'].filter(id=>EV.has(id));}}persist();counts();scrollStates[next]=0;displayScreen(next);toast('実在の企画を使った仮の参加計画です。予約・申込は行っていません。');}
function exitDemo(){if(!demo)return;closeModal();demo=false;model=userModel;planFocus='';undo=null;counts();displayScreen('plan');toast('操作例を終了しました。あなたの確認用予定に戻りました。');}
function resetTime(key){const x=model.entries[key];if(!x)return;rememberUndo();x.start='';x.end='';x.partialConfirmed=false;closeModal();changed();toast('自分の参加時間を、公表されている開催時間に戻しました。',true);}
function safeFocusAfter(d){requestAnimationFrame(()=>{let node;if(d.candidate)node=$$('[data-candidate]').find(el=>el.dataset.candidate===d.candidate);else if(d.add)node=$$('[data-add]').find(el=>el.dataset.add===d.add&&el.dataset.day===d.day);if(node)node.focus({preventScroll:true});});}
document.addEventListener('click',ev=>{const b=ev.target.closest('button,a');if(!b)return;const d=b.dataset;
 if(d.screen){ev.preventDefault();closeModal();displayScreen(d.screen);return;}
 if(d.candidate){toggleCandidate(d.candidate);safeFocusAfter(d);return;}if(d.add){add(d.add,d.day);safeFocusAfter(d);return;}if(d.detail){detail(d.detail,d.day);return;}
 if(d.remove){remove(d.remove);return;}if(d.registration){registration(d.registration);return;}if(d.editTime){editTime(d.editTime);return;}if(d.resetTime){resetTime(d.resetTime);return;}if(d.editLeg){editLeg(d.editLeg);return;}if(d.review){review(d.review);return;}if(d.focusPlan){focusPlan(d.focusPlan);return;}
 if(d.showStop){const m=mapViews.get('plan-map');if(m?.items.some(x=>x.key===d.showStop&&geo(x.venue))){m.selectKey(d.showStop);m.root.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}else{const x=model.entries[d.showStop];if(x)detail(x.id,x.day);toast('この会場は位置未確認、または時刻未確定のため訪問順の対象外です。');}return;}
 if(d.planDay){model.day=d.planDay;planFocus='';persist();renderCurrent();return;}if(d.planView){model.view=d.planView;persist();renderPlan();return;}if(d.date){filters.day=d.date;closeModal();screen='explore';displayScreen('explore',{scroll:false});filterChanged();return;}
 if(d.quick){const [key,value]=d.quick.split(':');filters[key]=filters[key]===value?baseFilters[key]:value;filterChanged();return;}
 if(d.clearFilter){const key=d.clearFilter;if(Object.hasOwn(baseFilters,key))filters[key]=baseFilters[key];filterChanged();return;}
 if(d.mapMode){mapViews.get(d.map)?.setMode(d.mapMode);return;}if(d.mapZoom){mapViews.get(d.map)?.changeZoom(+d.mapZoom);return;}if(d.mapFit){mapViews.get(d.mapFit)?.fit();return;}if(d.mapGroup!==undefined){mapViews.get(d.map)?.selectGroup(+d.mapGroup);return;}if(d.mapItem){mapViews.get(d.map)?.selectKey(d.mapItem);return;}
 if(d.searchVenue){filters.venue=d.searchVenue;filters.q='';filters.candidates=false;filters.limit=18;if(!occurrences().length)filters.day='any';scrollStates.explore=0;displayScreen('explore');updateURL();return;}
 if(d.searchGap){searchGap(d.searchGap);return;}if(d.gap){suggestGap(d.gap);return;}if(d.addSuggestion!==undefined){const p=pending,sel=p?.picks?.[+d.addSuggestion];if(sel){closeModal();add(sel.e.id,p.day,{times:[time(sel.start),time(sel.end)]});}return;}
 if(d.googleEvent){googleEvent(d.googleEvent,d.day);return;}if(d.icsEvent){const r=eventRow(d.icsEvent,d.day);if(!r){toast('時刻や開催条件の確認が必要です。');return;}download('ramen-event-'+d.day+'.ics',createICS([r]),'text/calendar;charset=utf-8');toast(dayName(d.day)+'の1枠を保存しました。');return;}
 const a=d.action;if(!a)return;
 if(a==='dismiss-toast')$('#toast').classList.remove('visible');else if(a==='help')openHelp();else if(a==='close-modal')closeModal();else if(a==='filters')openFilters();else if(a==='settings')openSettings();else if(a==='demo'||a==='demo-today')startDemo(a==='demo-today'?'today':'plan');else if(a==='exit-demo')exitDemo();
 else if(a==='clear-query'){filters.q='';filterChanged();$('#query').focus();}else if(a==='candidate-filter'){filters.candidates=!filters.candidates;filterChanged();}
 else if(a==='reset-filters'||a==='reset-filters-modal'){filters={...baseFilters,day:filters.day};closeModal();displayScreen('explore',{scroll:false});filterChanged();}
 else if(a==='more'){filters.limit+=18;renderExplore();}else if(a==='layout'){filters.layout=filters.layout==='cards'?'list':'cards';filterChanged();}
 else if(a==='related-dates'){openModal('dates','参加する日程を選ぶ',`<p class="modal-intro">本会期以外の関連日程も確認できます。開催日と利用条件は各イベントの主催者案内が基準です。</p><div class="detail-actions"><button class="button secondary" data-date="main">本会期 10/7–11</button><button class="button secondary" data-date="pre">9/30–10/6</button><button class="button secondary" data-date="after">10/12–14</button></div><div class="field-grid">${allDays.map(day=>`<button class="button secondary" data-date="${day}" style="margin:5px 0">${dayName(day)}</button>`).join('')}</div>`);}
 else if(a==='gf-search'){filters={...baseFilters,day:'any',venue:'garraway'};scrollStates.explore=0;displayScreen('explore');updateURL();}
 else if(a==='undo'){if(undo&&undo.demo===demo){model=undo.model;if(!demo)userModel=model;undo=null;changed();toast('直前の変更を元に戻しました。');}}
 else if(a==='replace-related'||a==='keep-related'){const p=pending;closeModal();add(p.id,p.day,{force:true,removeKeys:a==='replace-related'?p.keys:[],times:p.times});}
 else if(a==='reset-leg'){const key=pending?.key;if(key){rememberUndo();delete model.legs[key];closeModal();changed();toast('徒歩の目安による自動計算に戻しました。',true);}}
 else if(a==='export')openExport();else if(a==='export-ics')exportICS();else if(a==='copy-plan')copyPlan();else if(a==='print-plan')printPlan();else if(a==='backup')backup();else if(a==='import')importFile();else if(a==='import-legacy')importLegacy();else if(a==='download-text'){const text=$('#copy-text')?.value||shareText(exportDays());download('ramen-plan.txt',text,'text/plain;charset=utf-8');toast('予定のテキストファイルを保存しました。');}
 else if(a==='go-plan'){$('#toast').classList.remove('visible');closeModal();displayScreen('plan');$('#plan-content').scrollIntoView({block:'start'});}
 else if(a==='merge-import'){const incoming=pending?.model;if(!incoming)return;rememberUndo();model.candidates=[...new Set([...model.candidates,...incoming.candidates])];model.entries={...incoming.entries,...model.entries};/* Current settings/legs have priority when merging. */model.legs={...incoming.legs,...model.legs};closeModal();changed();displayScreen('plan');toast('既存の予定を優先して、読み込み内容を追加しました。',true);}
 else if(a==='replace-import-confirm'){openModal('import-confirm','今の確認用予定を置き換えますか',`<p class="modal-intro">現在の${Object.keys(model.entries).length}件の予定・候補・移動設定を、選んだファイルの内容で置き換えます。必要な場合は先にバックアップしてください。本番サイトの保存データは変更しません。</p><div class="merge-choice"><button class="button secondary" data-action="backup">今の内容をバックアップ</button><button class="button danger" data-action="replace-import">読み込み内容で置き換える</button><button class="button secondary" data-action="close-modal">中止する</button></div>`);}
 else if(a==='replace-import'){if(!pending?.model)return;rememberUndo();model=hydrate(pending.model);if(!demo)userModel=model;closeModal();changed();displayScreen('plan');toast('選んだファイルの内容を読み込みました。',true);}
});
let queryTimer;
$('#query').addEventListener('input',e=>{if(e.isComposing)return;clearTimeout(queryTimer);queryTimer=setTimeout(()=>{filters.q=e.target.value.slice(0,160);filterChanged();},180);});
$('#query').addEventListener('compositionend',e=>{clearTimeout(queryTimer);filters.q=e.target.value.slice(0,160);filterChanged();});
document.addEventListener('change',async e=>{const target=e.target;
 if(target.id==='sort'){filters.sort=target.value;filterChanged();}else if(target.id==='detail-date')detail(target.dataset.id,target.value);else if(target.id==='export-scope'){exportScope=target.value;updateExportSummary();$('#export-error').hidden=true;}else if(target.id==='map-scope'){mapScope=target.value;renderAllMap();}else if(target.id==='map-area'){mapArea=target.value;renderAllMap();}else if(target.id==='today-test-time'){if(min(target.value)!==null){todayTestTime=target.value;renderToday();}}else if(target.id==='leg-mode'){const l=findLeg(pending?.key);$('#leg-minutes').value='';const a=$('#leg-form a');if(l&&a)a.href=directions(l.from.venue,l.to.venue,target.value);}
 else if(target.id==='import-file'){const file=target.files?.[0];if(!file)return;if(file.size>2*1024*1024){formError('2MB以下の予定ファイルを選んでください。');return;}try{const raw=JSON.parse(await file.text()),m=hydrate(raw);importConfirm(m,raw.sample===true);}catch{formError('このガイドの有効な .json ファイルを読み込めませんでした。現在の保存は変更していません。');}}
});
document.addEventListener('submit',ev=>{const form=ev.target;if(!form.matches('#filter-form,#leg-form,#visit-form,#registration-form,#review-form,#settings-form'))return;ev.preventDefault();const data=new FormData(form);
 if(form.id==='filter-form'){const from=data.get('from')||'',until=data.get('until')||'';if(from&&until&&min(from)>=min(until)){formError('終了の上限は、開始の下限より後にしてください。');return;}for(const name of ['venue','category','area','period','fee','kind','from','until'])filters[name]=String(data.get(name)||'');filters.known=data.has('known');filters.candidates=data.has('candidates');closeModal();displayScreen('explore',{scroll:false});filterChanged();}
 else if(form.id==='leg-form'){const l=findLeg(form.dataset.key);if(!l)return;const mode=String(data.get('mode')),str=String(data.get('minutes')||'').trim(),value=str===''?null:Number(str);if(str!==''&&(!Number.isInteger(value)||value<0||value>720)){formError('所要時間は0〜720分の整数で入力してください。');return;}if(mode!=='walking'&&value===null){formError('公共交通・車・タクシーは、地図で確認した所要時間を入力してください。');return;}rememberUndo();model.legs[l.key]={mode,minutes:value,signature:l.signature};closeModal();changed();toast('移動方法と所要時間を反映しました。',true);}
 else if(form.id==='visit-form'){const key=form.dataset.key,x=model.entries[key],e=EV.get(x?.id);if(!x||!e)return;const a=String(data.get('start')),b=String(data.get('end')),s=min(a),t=min(b),[ps,pe]=slot(e,x.day).map(min);if(s===null||t===null||t<=s){formError('参加終了は参加開始より後にしてください。');return;}if(s<ps||t>pe){formError('主催者が公表している開催時間の範囲内で設定してください。');return;}const partial=s!==ps||t!==pe;if(partial&&!isFlexible(e)&&!data.has('partial')){formError('途中入退場の可否を主催者に確認し、確認欄にチェックしてください。');return;}rememberUndo();x.start=partial?a:'';x.end=partial?b:'';x.partialConfirmed=partial&&(isFlexible(e)||data.has('partial'));closeModal();changed();toast('自分の参加時間を変更しました。開催時間そのものは変更していません。',true);}
 else if(form.id==='registration-form'){const x=model.entries[form.dataset.key];if(!x)return;x.registration=String(data.get('registration'));closeModal();changed();toast('申込状況を自分用メモとして記録しました。');}
 else if(form.id==='review-form'){if(!data.has('read'))return;const x=model.entries[form.dataset.key],e=EV.get(x?.id);if(!e)return;x.snapshot=signature(e,x.day);x.reviewed=signature(e,x.day);closeModal();changed();toast('開催条件の確認を記録しました。未確定の時刻は引き続き確認が必要です。');}
 else if(form.id==='settings-form'){model.settings.buffer=+data.get('buffer');model.settings.speed=+data.get('speed');closeModal();changed();toast('予備時間と徒歩の計算条件を反映しました。');}
});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
$('#modal').addEventListener('cancel',()=>{modalType='';});
window.addEventListener('popstate',()=>{parseURL();displayScreen(screen,{history:false,scroll:false});});
window.addEventListener('afterprint',()=>{$('#print-root').setAttribute('aria-hidden','true');});
setInterval(()=>{if(demo||$('#modal').open)return;if(screen==='today')renderToday();else if(screen==='plan'&&model.day===nowJST().day){const box=$('.plan-now');if(box&&!box.contains(document.activeElement))box.outerHTML=nextPlanHTML(itinerary(model.day));}},60000);
// Public, read-only snapshots and deterministic helpers for regression tests and future data integration.
window.GuideApp={getState:()=>structuredClone(model),getFilters:()=>({...filters}),itinerary,calendarRows,createICS,stamp,signature,estimate,knownTime,hydrate,occurrences,shareText,startDemo,displayScreen,add,remove,toggleCandidate,eventRow,exportICS,
 replaceCatalog(next){if(!next||!Array.isArray(next.events)||!Array.isArray(next.venues))throw Error('Invalid catalog');D=next;window.RAMEN_CATALOG=next;rebuildIndexes();renderCurrent();},
 getData:()=>structuredClone(D),setExportScope(value){exportScope=value==='all'?'all':'day';},setDay(day){if(dateOK(day)){model.day=day;renderCurrent();}},getMapItems:()=>planItems(itinerary(model.day)),migratePreview(raw){model=hydrate(raw);if(!demo)userModel=model;changed();}};
if(!CFG.preview)$$('.preview-bar').forEach(e=>e.hidden=true);
$$('[data-source-date]').forEach(el=>el.textContent='掲載データ：'+(D.meta.fetchedAt||D.meta.checkedAt));
counts();displayScreen(screen,{history:false,scroll:false});
if(CFG.demo||new URLSearchParams(location.search).get('demo')==='1')startDemo(CFG.start||'plan');
const initialParams=new URLSearchParams(location.search);if(initialParams.get('event'))detail(initialParams.get('event'),initialParams.get('on'));
})();
