/* RAMEN itinerary planner: local-only selections, conservative estimates, no routing API claims. */
'use strict';
(()=>{
const G=window.RamenGuide,D=window.RAMEN_CATALOG;if(!G||!D)return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const events=new Map(D.events.map(e=>[e.id,e])),venues=new Map(D.venues.map(v=>[v.id,v]));
const KEY='ramen-itinerary-v1',OLD='garrawayf-ramen-city-2026-favorites-v2',ROOT='https://mobilitydlab.com/GarrawayFapp.github.io/ramen-tech-2026/';
const DEFAULT={version:1,entries:{},legs:{},buffer:10,speed:70,day:'',view:'timeline'};
let model=structuredClone(DEFAULT),storageOK=true,migration=false;
const minute=t=>/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(t||'')?Number(t.slice(0,2))*60+Number(t.slice(3)):null;
const clock=n=>n===null||!Number.isFinite(n)?'—':`${n>=1440?'翌日 ':''}${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const dayName=d=>`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}（${['日','月','火','水','木','金','土'][new Date(d+'T12:00:00+09:00').getUTCDay()]}）`;
const keyOf=(id,day)=>id+'|'+day;
function signature(e,day){return JSON.stringify([e.title,e.venue,e.room,day,...G.getTime(e,day),e.calendarBlocked||false,e.status,e.fee,e.dates.includes(day)]);}
function entry(id,day){const e=events.get(id);return {id,day,start:'',end:'',snapshot:signature(e,day),title:e.title,venue:e.venue};}
function hydrate(raw){if(!raw||raw.version!==1||typeof raw.entries!=='object'||Array.isArray(raw.entries))return structuredClone(DEFAULT);const out=structuredClone(DEFAULT);for(const [k,v] of Object.entries(raw.entries||{}).slice(0,600)){if(v&&typeof v.id==='string'&&/^2026-\d{2}-\d{2}$/.test(v.day)&&k===keyOf(v.id,v.day)){out.entries[k]={id:v.id,day:v.day,start:minute(v.start)!==null?v.start:'',end:minute(v.end)!==null?v.end:'',snapshot:typeof v.snapshot==='string'?v.snapshot.slice(0,4000):'',title:String(v.title||'保存したイベント').slice(0,600),venue:String(v.venue||'')};}}
for(const [k,v] of Object.entries(raw.legs||{}).slice(0,600)){if(v&&['walking','transit','driving'].includes(v.mode))out.legs[k]={mode:v.mode,minutes:Number.isInteger(v.minutes)&&v.minutes>=0&&v.minutes<=720?v.minutes:null,signature:String(v.signature||'').slice(0,2000)};}
out.buffer=[0,5,10,15,20,30].includes(Number(raw.buffer))?Number(raw.buffer):10;out.speed=[50,70,90].includes(Number(raw.speed))?Number(raw.speed):70;out.day=typeof raw.day==='string'?raw.day:'';out.view=raw.view==='table'?'table':'timeline';return out;}
try{const raw=localStorage.getItem(KEY);if(raw)model=hydrate(JSON.parse(raw));else{let old=JSON.parse(localStorage.getItem(OLD)||'[]');if(Array.isArray(old))for(const id of old){const e=events.get(id);if(e)for(const day of e.dates)model.entries[keyOf(id,day)]=entry(id,day);}migration=Object.keys(model.entries).length>0;}}catch{storageOK=false;}
let toastTimer;function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4000);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(model));storageOK=true;}catch{storageOK=false;toast('端末に保存できません。この画面を閉じるまで有効です。');}}
function syncInterest(id){G.setSaved?.(id,Object.values(model.entries).some(x=>x.id===id));}
function toggle(id,day){const e=events.get(id);if(!e||!e.dates.includes(day))return;const k=keyOf(id,day),remove=!!model.entries[k];if(remove)delete model.entries[k];else model.entries[k]=entry(id,day);model.day=day;persist();syncInterest(id);render();toast(remove?'この日の予定から外しました':`${dayName(day)} の予定に追加しました。移動も予定表で確認できます。`);}
function remove(k){const x=model.entries[k];if(!x)return;delete model.entries[k];persist();syncInterest(x.id);render();}
function rows(day){return Object.entries(model.entries).filter(([,x])=>x.day===day).map(([key,x])=>{const e=events.get(x.id),missing=!e||!e.dates.includes(x.day),times=!missing?G.getTime(e,x.day):[null,null],s=minute(x.start||times[0]),t=minute(x.end||times[1]),changed=!missing&&x.snapshot!==signature(e,x.day);let invalid=missing||s===null||t===null||t<=s||!G.canCalendar(e,x.day);if(!invalid&&(s<minute(times[0])||t>minute(times[1])))invalid=true;return {key,x,e,missing,changed,start:s,end:t,invalid,venue:venues.get(e?.venue||x.venue),sourceTimes:times};}).sort((a,b)=>(a.invalid?1:0)-(b.invalid?1:0)||(a.start??1e5)-(b.start??1e5)||a.key.localeCompare(b.key));}
function point(row){const v=row.venue,p=v?.geo;if(!p||!Number.isFinite(p.lat)||!Number.isFinite(p.lng)||p.status!=='located')return null;return p;}
function haversine(a,b){const rad=Math.PI/180,dlat=(b.lat-a.lat)*rad,dlng=(b.lng-a.lng)*rad,q=Math.sin(dlat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
function legKey(a,b){return a.key+'~'+b.key;}
function legSignature(a,b){const geo=r=>{const p=point(r);return p?[p.lat,p.lng,p.address]:null;};return JSON.stringify([a.e?.venue,a.e?.room,b.e?.venue,b.e?.room,geo(a),geo(b)]);}
function locationText(r){return [r.venue?.name,point(r)?.address||r.venue?.address||'',r.venue?.area==='その他'?'':'福岡'].filter(Boolean).join(' ');}
function directions(a,b,mode){const u=new URL('https://www.google.com/maps/dir/');u.search=new URLSearchParams({api:'1',origin:locationText(a),destination:locationText(b),travelmode:mode});return u.href;}
function transfer(a,b){const key=legKey(a,b),saved=model.legs[key],sameVenue=a.e?.venue===b.e?.venue,knownVenue=a.venue&&!['tbd','private','city','kyushu-venues','v-9c4fea060c'].includes(a.venue.id),mode=saved?.mode||'walking',sig=legSignature(a,b),manualValid=saved?.minutes!==null&&saved?.minutes!==undefined&&saved.signature===sig;
let duration=null,method='',distance=null;if(manualValid){duration=saved.minutes;method='自分で確認した所要時間';}else if(mode==='walking'&&sameVenue&&knownVenue){duration=a.e.room&&a.e.room===b.e.room?0:3;method=duration?'同じ施設内の移動目安':'同じ部屋';}else if(mode==='walking'&&point(a)&&point(b)){distance=haversine(point(a),point(b));if(distance<=5000){duration=distance<35?5:Math.max(5,Math.ceil(distance*1.35/model.speed/5)*5);method=distance<35?'同じ建物付近・館内移動の目安':'直線距離からの徒歩目安';}else method='長距離のため、地図で確認して入力';}else method=mode==='walking'?'会場位置未確認・移動時間を入力':'地図で所要時間を確認して入力';
return {key,mode,duration,method,distance,manual:manualValid,stale:!!saved&&saved.minutes!==null&&!manualValid,signature:sig,url:directions(a,b,mode)};}
function itinerary(day){const all=rows(day),ordered=all.filter(r=>!r.invalid),unresolved=all.filter(r=>r.invalid),legs=[],warnings=[],buffers=[];let ready=null,previous=null;for(const r of ordered){r.arrival=null;r.late=0;if(previous){const leg=transfer(previous,r);leg.from=previous;leg.to=r;leg.depart=ready;leg.arrive=leg.duration===null||ready===null?null:ready+leg.duration;leg.available=leg.arrive===null?null:r.start-leg.arrive-model.buffer;leg.buffer=model.buffer;leg.late=leg.available===null?null:Math.max(0,-leg.available);legs.push(leg);r.arrival=leg.arrive;r.late=leg.late;if(leg.available===null)warnings.push('移動時間を確認してください');else if(leg.available<0)warnings.push('移動・予備時間が不足しています');if(leg.arrive!==null&&leg.buffer)buffers.push({start:leg.arrive,end:leg.arrive+leg.buffer});ready=leg.arrive===null?null:Math.max(r.end,leg.arrive+leg.buffer);}else ready=r.end;previous=r;}
for(const r of all)if(r.changed)warnings.push('開催情報が変わっています');if(unresolved.length)warnings.push('時刻・会場などが要確認の予定があります');return {day,all,ordered,unresolved,legs,buffers,warnings:[...new Set(warnings)],travel:legs.reduce((s,x)=>s+(x.duration||0),0),unknown:legs.filter(l=>l.duration===null).length};}
function selectButton(id,day,short=false){const selected=!!model.entries[keyOf(id,day)];return `<button type="button" class="plan-select${selected?' selected':''}" data-plan-add="${esc(id)}" data-plan-day="${day}" aria-pressed="${selected}">${selected?'✓ 予定に追加済み':short?'＋ 予定に追加':'＋ この日の予定に追加'}</button>`;}
function enhance(){for(const card of $$('.event-card')){const b=card.querySelector('[data-detail]');if(!b)continue;const e=events.get(b.dataset.detail),day=b.dataset.on;if(!e||!day)continue;card.classList.toggle('at-garraway',e.venue==='garraway');const bottom=card.querySelector('.card-bottom');let slot=bottom?.querySelector('.plan-select-slot');if(bottom&&!slot){slot=document.createElement('span');slot.className='plan-select-slot';bottom.prepend(slot);}if(slot)slot.innerHTML=selectButton(e.id,day);if(e.venue==='garraway'&&!card.querySelector('.garraway-label')){const label=document.createElement('span');label.className='garraway-label';label.textContent='GARRAWAY F 開催';card.querySelector('.card-labels')?.prepend(label);}}
const detail=$('#detail-body'),save=detail?.querySelector('[data-save]');if(save){const id=save.dataset.save,day=save.dataset.on||$('#detail-day')?.value||events.get(id)?.dates[0];let slot=detail.querySelector('.detail-plan-slot');if(!slot){slot=document.createElement('div');slot.className='detail-plan-slot';save.after(slot);}if(day)slot.innerHTML=selectButton(id,day);}}
function featured(){const root=$('#garraway-featured');if(!root)return;const list=D.events.filter(e=>e.venue==='garraway'&&e.kind==='event'),manual=list.filter(e=>e.origin==='主催者予定');$('#garraway-feature-count').textContent=String(D.events.filter(e=>e.venue==='garraway').length);
$('#garraway-highlights').innerHTML=[7,8,9].map(d=>{const day=`2026-10-${String(d).padStart(2,'0')}`,es=manual.filter(e=>e.dates.includes(day)).sort((a,b)=>(G.getTime(a,day)[0]||'').localeCompare(G.getTime(b,day)[0]||''));return `<div class="gf-day"><h3>${dayName(day)}</h3>${es.map(e=>{const t=G.getTime(e,day);return `<article><p class="gf-time">${esc(t[0]||'確認中')}–${esc(t[1]||'')}</p><button class="gf-title" data-detail="${esc(e.id)}" data-on="${day}">${esc(e.title)}</button><p class="gf-fee">${esc(e.fee)}${e.calendarBlocked?' / 要確認':''}</p>${selectButton(e.id,day,true)}</article>`;}).join('')}</div>`;}).join('');}
function eventHTML(r,i){const e=r.e,own=e?.venue==='garraway';return `<article class="plan-event ${own?'plan-garraway':''}" data-plan-key="${esc(r.key)}"><div class="plan-time"><span>${r.invalid?'要確認':clock(r.start)}</span><small>${r.invalid?'':clock(r.end)}</small></div><div class="plan-content"><div class="plan-card-top"><span class="plan-type">${own?'GARRAWAY F':'EVENT '+String(i+1).padStart(2,'0')}</span><button class="plan-remove" data-plan-remove="${esc(r.key)}" aria-label="${esc(e?.title||r.x.title)}をこの日の予定から削除">×</button></div><h4>${esc(e?.title||r.x.title)}</h4><p class="plan-venue">${esc(r.venue?.name||'会場要確認')}${e?.room?'<br><small>'+esc(e.room)+'</small>':''}</p>${r.x.start||r.x.end?'<p class="plan-small">自分の参加時間 / 公表時間 '+esc(r.sourceTimes.join('–'))+'</p>':''}${r.late>0?'<p class="plan-warning">この順序では予備時間を含め '+r.late+'分不足。参加時間・移動手段を見直してください。</p>':''}${r.missing?'<p class="plan-warning">保存時の開催日が現在のデータにありません。主催者案内で確認してください。</p>':r.invalid?'<p class="plan-warning">時刻未公表・中止表記・情報の不一致などがあります。移動計算とカレンダー出力から除外しています。</p>':''}${r.changed?'<div class="plan-warning">保存後に開催情報が変わりました。最新の詳細をご確認ください。<button data-plan-ack="'+esc(r.key)+'">変更を確認した</button></div>':''}<div class="plan-links">${e?'<button data-detail="'+esc(e.id)+'" data-on="'+r.x.day+'">開催・参加条件を確認 ↗</button>':''}</div>${!r.invalid?`<details class="visit-editor"><summary>参加する時間を調整</summary><form data-visit="${esc(r.key)}"><label>到着<input type="time" name="start" value="${clock(r.start)}" required></label><label>退出<input type="time" name="end" value="${clock(r.end)}" required></label><button type="submit">反映</button><button type="button" data-plan-reset-time="${esc(r.key)}">公表時間に戻す</button><p>途中入退場が可能かは主催者に確認してください。</p></form></details>`:''}</div></article>`;}
function legHTML(l){const mode={walking:'徒歩',transit:'公共交通',driving:'車・タクシー'}[l.mode];return `<div class="plan-leg ${l.available!==null&&l.available<0?'leg-warning':''}" data-leg="${esc(l.key)}"><div class="leg-time">${clock(l.depart)}<br><span>↓</span><br>${clock(l.arrive)}</div><div class="leg-content"><span class="plan-type">MOVE TO NEXT</span><h4>${mode} ${l.duration===null?'所要時間を確認':(l.manual?'':'約 ')+l.duration+'分'}</h4><p>${esc(l.from.venue?.name||'会場未確認')} → ${esc(l.to.venue?.name||'会場未確認')}</p><p class="plan-small">${esc(l.method)}${l.distance!==null?' / 直線 '+(l.distance/1000).toFixed(2)+'km':''}</p>${l.stale?'<p class="plan-warning">会場情報の変更により、以前の手入力時間を無効にしました。</p>':''}<div class="leg-controls"><label>移動手段<select data-leg-mode="${esc(l.key)}"><option value="walking" ${l.mode==='walking'?'selected':''}>徒歩（目安を自動計算）</option><option value="transit" ${l.mode==='transit'?'selected':''}>公共交通（時間を入力）</option><option value="driving" ${l.mode==='driving'?'selected':''}>車・タクシー（時間を入力）</option></select></label><label>確認した時間<input type="number" min="0" max="720" step="1" inputmode="numeric" data-leg-minutes="${esc(l.key)}" value="${l.manual?l.duration:''}" placeholder="分を入力" aria-label="この移動で確認した所要時間（分）"></label></div><a class="leg-map" href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">Googleマップで経路・時間を確認 ↗</a><p class="plan-small">公共交通は地図側で利用日・出発時刻を設定。手入力には待ち時間・乗換も含めてください。</p><p class="leg-result">${l.available===null?'時間未確定：到着見込みは未計算':l.available<0?'⚠ 移動＋予備 '+model.buffer+'分では '+(-l.available)+'分不足':'移動後の予備 '+model.buffer+'分 ＋ 自由時間 '+l.available+'分'}</p></div></div>`;}
function render(){const days=[...new Set(Object.values(model.entries).map(x=>x.day))].sort(),count=Object.keys(model.entries).length;if(!days.includes(model.day))model.day=days[0]||'2026-10-07';$$('[data-plan-count]').forEach(e=>e.textContent=count);$('#planner-count').textContent=count;$('#planner-empty').hidden=count>0;$('#planner-filled').hidden=count===0;$('#planner-days').innerHTML=days.map(d=>`<button data-plan-date="${d}" aria-pressed="${d===model.day}">${dayName(d)}<span>${rows(d).length}件</span></button>`).join('');$('#planner-migration').hidden=!migration;$('#planner-storage').hidden=storageOK;$('#plan-buffer').value=model.buffer;$('#plan-speed').value=model.speed;const p=itinerary(model.day);$('#plan-day-title').textContent=dayName(model.day);$('#plan-summary').textContent=`${p.all.length}件 / 移動 ${p.unknown?'確認済み分 ':''}${p.travel}分${p.unknown?' ＋ 未確認 '+p.unknown+'区間':''}`;$('#plan-alert').hidden=!p.warnings.length;$('#plan-alert').textContent=p.warnings.join(' / ');$('#plan-timeline').innerHTML=p.ordered.map((r,i)=>eventHTML(r,i)+(p.legs[i]?legHTML(p.legs[i]):'')).join('')+(p.unresolved.length?'<h3 class="plan-unresolved-heading">時刻などを確認してから組み込む予定</h3>'+p.unresolved.map((r,i)=>eventHTML(r,i)).join(''):'');$('#plan-print-title').textContent=`RAMEN TECH / ${dayName(model.day)} マイスケジュール`;
const body=[];p.ordered.forEach((r,i)=>{body.push(`<tr><td>${clock(r.start)}–${clock(r.end)}</td><td>${esc(r.e.title)}</td><td>${esc(r.venue?.name||'')}</td><td>${r.changed?'開催情報変更':r.x.start||r.x.end?'参加時間を調整':''}</td></tr>`);const l=p.legs[i];if(l)body.push(`<tr class="table-leg"><td>${clock(l.depart)}–${clock(l.arrive)}</td><td>移動 ${l.duration===null?'要確認':l.duration+'分'}${!l.manual?'（目安）':''}</td><td>${esc(l.from.venue?.name)} → ${esc(l.to.venue?.name)}</td><td>${l.available===null?'未計算':l.available<0?-l.available+'分不足':'予備 '+model.buffer+'分 / 空き '+l.available+'分'}</td></tr>`);});$('#plan-table-body').innerHTML=body.join('');$('#plan-timeline').hidden=model.view==='table';$('#plan-table-view').hidden=model.view!=='table';$('#plan-table-note').textContent=p.unresolved.length?`${p.unresolved.length}件は時刻等が要確認です。タイムライン表示で確認してください。`:'';$$('[data-plan-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.planView===model.view));enhance();featured();}
function openPlanner(){render();$('#planner').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('#plan-day-title').focus({preventScroll:true});}
function icsEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');}
function fold(s){let res='',part='',len=0;for(const c of s){const n=new TextEncoder().encode(c).length;if(len+n>73){res+=part+'\r\n';part=' ';len=1;}part+=c;len+=n;}return res+part;}
function stamp(day,n){const d=new Date(day+'T00:00:00+09:00');d.setTime(d.getTime()+n*60000);return d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');}
function calendarRows(p){const out=p.ordered.filter(r=>!r.changed).map(r=>({id:r.key,title:r.e.title,location:locationText(r),start:r.start,end:r.end,note:'自分の参加予定。主催者の開催時間 '+r.sourceTimes.join('–')+'。予約ではありません。情報の変更は自動同期されません。',url:ROOT+'?date=any&event='+encodeURIComponent(r.e.id)+'&on='+r.x.day}));for(const l of p.legs){if(l.duration===null||l.depart===null||l.duration===0)continue;out.push({id:'move-'+l.key,title:`【${l.manual?'手入力':'徒歩・目安'}】${l.from.venue.name} → ${l.to.venue.name}`,location:l.to.venue.name,start:l.depart,end:l.arrive,note:l.method+'。実際の経路・交通状況・到着を保証しません。'+l.url,url:l.url});if(model.buffer)out.push({id:'buffer-'+l.key,title:'【移動後の予備時間】'+l.to.venue.name,location:l.to.venue.name,start:l.arrive,end:l.arrive+model.buffer,note:'入館・受付・移動の予備時間。',url:ROOT});}return out.sort((a,b)=>a.start-b.start);}
function exportPlan(){const p=itinerary(model.day);if(!p.all.length){toast('先に参加したいイベントを選んでください');return;}if(p.warnings.length){toast('予定表の要確認・移動時間不足・開催情報の変更を確認してから書き出してください');return;}const entries=calendarRows(p),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Garraway F//RAMEN itinerary//JA','CALSCALE:GREGORIAN'],now=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');for(const x of entries)lines.push('BEGIN:VEVENT','UID:'+icsEscape(x.id)+'@ramen-plan.mobilitydlab.com','DTSTAMP:'+now,'DTSTART:'+stamp(p.day,x.start),'DTEND:'+stamp(p.day,x.end),'SUMMARY:'+icsEscape(x.title),'LOCATION:'+icsEscape(x.location),'DESCRIPTION:'+icsEscape(x.note),'URL:'+x.url,'STATUS:TENTATIVE','END:VEVENT');lines.push('END:VCALENDAR');const u=URL.createObjectURL(new Blob([lines.map(fold).join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='ramen-plan-'+p.day+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);toast('イベント・移動・予備時間をカレンダーファイルにしました');}
async function copyPlan(){const p=itinerary(model.day),lines=[`RAMEN TECH ${dayName(p.day)} マイスケジュール`];if(p.warnings.length)lines.push('【要確認】'+p.warnings.join(' / '));for(let i=0;i<p.ordered.length;i++){const r=p.ordered[i];lines.push(`${clock(r.start)}–${clock(r.end)} ${r.e.title} / ${r.venue?.name}`);const l=p.legs[i];if(l)lines.push(`${clock(l.depart)}–${clock(l.arrive)} 移動 ${l.duration===null?'要確認':l.duration+'分'}（${l.method}） → ${l.to.venue?.name} / 予備${model.buffer}分`);}for(const r of p.unresolved)lines.push('要確認：'+(r.e?.title||r.x.title));lines.push('移動は目安です。出発前に主催者・地図を確認。',ROOT);try{await navigator.clipboard.writeText(lines.join('\n'));toast('予定表をコピーしました');}catch{toast('コピーできません。予定表の印刷機能をご利用ください');}}
document.addEventListener('click',ev=>{const b=ev.target.closest('button,a');if(!b)return;const d=b.dataset;if(d.planAdd){toggle(d.planAdd,d.planDay);return;}if(d.planOpen!==undefined){ev.preventDefault();openPlanner();}if(d.planRemove)remove(d.planRemove);if(d.planDate){model.day=d.planDate;persist();render();}if(d.planView){model.view=d.planView;persist();render();}if(d.planAck){const r=model.entries[d.planAck],e=r&&events.get(r.id);if(e){r.snapshot=signature(e,r.day);persist();render();}}if(d.planResetTime){model.entries[d.planResetTime].start='';model.entries[d.planResetTime].end='';persist();render();}if(d.planExport!==undefined)exportPlan();if(d.planCopy!==undefined)copyPlan();if(d.planPrint!==undefined){document.body.classList.add('printing-plan');window.print();}if(d.planGf!==undefined){ev.preventDefault();$('#garraway-featured').scrollIntoView({behavior:'smooth'});}if(d.planMigrateClose!==undefined){migration=false;$('#planner-migration').hidden=true;}});
document.addEventListener('change',ev=>{const t=ev.target;if(t.id==='plan-buffer'||t.id==='plan-speed'){model[t.id==='plan-buffer'?'buffer':'speed']=Number(t.value);persist();render();}const k=t.dataset.legMode||t.dataset.legMinutes;if(k){const l=itinerary(model.day).legs.find(x=>x.key===k);if(!l)return;let minutes=t.dataset.legMinutes?(t.value===''?null:Number(t.value)):null;if(minutes!==null&&(!Number.isInteger(minutes)||minutes<0||minutes>720)){toast('所要時間は0〜720分の整数で入力してください');t.value='';return;}model.legs[k]={mode:t.dataset.legMode?t.value:l.mode,minutes,signature:l.signature};persist();render();}});
document.addEventListener('submit',ev=>{const k=ev.target.dataset.visit;if(!k)return;ev.preventDefault();const x=model.entries[k],e=events.get(x.id),f=new FormData(ev.target),s=String(f.get('start')),t=String(f.get('end')),[start,end]=G.getTime(e,x.day);if(minute(s)===null||minute(t)===null||s>=t||s<start||t>end){toast('主催者の開催時間の範囲内で、到着より後の退出時刻を入力してください');return;}x.start=s;x.end=t;persist();render();toast('自分の参加時間を変更しました。途中入退場の可否は主催者に確認してください。');});
document.addEventListener('ramen:render',()=>enhance());
document.addEventListener('ramen:saved',ev=>{const {id,add,day}=ev.detail,e=events.get(id);if(!e)return;if(add){const on=e.dates.includes(day)?day:e.dates[0];model.entries[keyOf(id,on)]=entry(id,on);model.day=on;}else for(const [k,v] of Object.entries(model.entries))if(v.id===id)delete model.entries[k];persist();render();});
new MutationObserver(()=>{enhance();}).observe($('#detail-body'),{childList:true});
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-plan'));
window.addEventListener('storage',ev=>{if(ev.key===KEY){try{model=hydrate(JSON.parse(ev.newValue));render();}catch{}}});
new IntersectionObserver(items=>{const dock=$('.planner-dock');if(dock)dock.hidden=items.some(x=>x.isIntersecting);},{threshold:0.02}).observe($('#planner'));
persist();render();window.RamenPlanner={toggle,remove,itinerary,rows,transfer,calendarRows,exportPlan,open:openPlanner,get model(){return model},get storageOK(){return storageOK}};
})();
