// HERO photography direction: natural people + space + conversation + serendipity.
const heroImg=document.querySelector('.hero-photo img');if(heroImg){heroImg.src='https://drive.google.com/thumbnail?id=1J6Ne_puDhM-7GLyJ1b7n2AMLfLs8ai1u&sz=w2000';heroImg.alt='Garraway Fで人と人が自然につながる風景';heroImg.fetchPriority='high';}
const photo=(id,alt)=>`<figure><img src="https://drive.google.com/thumbnail?id=${id}&sz=w1400" alt="${alt}" loading="lazy"></figure>`;
const statement=document.querySelector('.statement');if(statement){statement.style.display='grid';statement.classList.add('living-photo-story');const old=statement.querySelector('.statement-photo');if(old)old.innerHTML='<img src="https://drive.google.com/thumbnail?id=1Flj3ETVCIChlwQpEvB4BbL19bT3EcQpb&sz=w1800" alt="Garraway Fで自然に生まれる対話" loading="lazy">';}
const facility=document.querySelector('#facility');if(facility&&!facility.querySelector('.living-gallery')){const gallery=document.createElement('div');gallery.className='living-gallery';gallery.innerHTML=`${photo('16bZEROOxM7CvTH3uOLZGiA8TSjNw8Bp3','Garraway Fで集う人たち')}${photo('1fXGYmJIcLKstmGU9TwTfHrdjC3OXh4be','Garraway Fでの対話')}${photo('1Nbri-E3AxcDM-Drofl2_6qf9wRjEqpow','Garraway Fで生まれる活動')}<p class="living-gallery-label">PEOPLE × SPACE / CONVERSATION / ACTION</p>`;facility.querySelector('.facility-grid')?.before(gallery);}
const els=[...document.querySelectorAll('.roles article')];const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:0,transform:'translateY(24px)'},{opacity:1,transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'});io.unobserve(e.target)}}),{threshold:.15});els.forEach(e=>io.observe(e));

const newsSection=document.querySelector('#news');
if(newsSection){
 const head=newsSection.querySelector('.news-live-head');if(head){const desc=head.querySelector('p:not(.kicker)');if(desc)desc.textContent='各SNSでイベント＆ニュースを発信中。Garraway Fの「今」をプレビューします。';const link=head.querySelector('a');if(link){link.textContent='CONNECT US';link.href='#social-preview';link.removeAttribute('target');}}
 const frame=newsSection.querySelector('.news-live-frame');
 if(frame){frame.id='social-preview';frame.className='social-preview';frame.innerHTML=`
 <article class="social-preview-card facebook"><div class="social-preview-head"><b>FACEBOOK</b><span>EVENTS & BUSINESS NEWS</span></div><div class="fb-page" data-href="https://www.facebook.com/garrawayf/" data-tabs="timeline,events" data-width="500" data-height="620" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false"><blockquote cite="https://www.facebook.com/garrawayf/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/garrawayf/">Garraway F</a></blockquote></div><a class="social-preview-link" href="https://www.facebook.com/garrawayf/" target="_blank" rel="noopener">FACEBOOKを開く ↗</a></article>
 <article class="social-preview-card x"><div class="social-preview-head"><b>X</b><span>GARRAWAY F NOW</span></div><a class="twitter-timeline" data-height="620" data-dnt="true" data-theme="light" data-chrome="noheader nofooter noborders transparent" href="https://twitter.com/garraway_f">Tweets by garraway_f</a><a class="social-preview-link" href="https://x.com/garraway_f" target="_blank" rel="noopener">Xを開く ↗</a></article>
 <article class="social-preview-card instagram"><div class="social-preview-head"><b>INSTAGRAM</b><span>LATEST 06 / LIVE FEED</span></div><div class="instagram-live-grid" id="instagram-live"><p class="instagram-loading">LOADING INSTAGRAM…</p></div><div class="instagram-accounts"><a href="https://www.instagram.com/garrawayf_lounge/" target="_blank" rel="noopener">@garrawayf_lounge ↗</a><a href="https://www.instagram.com/garrawayf_toshokan/" target="_blank" rel="noopener">LIBRARY ↗</a></div></article>`;}
 if(!document.querySelector('script[src*="connect.facebook.net"]')){const s=document.createElement('script');s.async=true;s.defer=true;s.crossOrigin='anonymous';s.src='https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v22.0';document.body.appendChild(s);}
 const loadX=()=>{if(window.twttr?.widgets){window.twttr.widgets.load(newsSection);return;}if(!document.querySelector('script[src*="platform.twitter.com/widgets.js"]')){const s=document.createElement('script');s.async=true;s.charset='utf-8';s.src='https://platform.twitter.com/widgets.js';s.onload=()=>window.twttr?.widgets?.load(newsSection);document.body.appendChild(s);}};loadX();
 const ig=document.querySelector('#instagram-live');if(ig){fetch('data/instagram.json?ts='+Date.now()).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{const posts=(data.posts||[]).slice(0,6);if(!posts.length)throw new Error();ig.innerHTML=posts.map((p,i)=>{const d=p.timestamp?new Date(p.timestamp):null;const date=d&&!isNaN(d)?d.toLocaleDateString('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit'}):'';const reel=p.media_type==='VIDEO'?'<span class="ig-reel">REEL</span>':'';return `<a class="ig-post" href="${p.permalink}" target="_blank" rel="noopener"><div class="ig-media"><img src="${p.image}" alt="Instagram post ${i+1}" loading="lazy">${reel}</div><div class="ig-meta"><time>${date}</time><span>${String(i+1).padStart(2,'0')}</span></div></a>`}).join('')}).catch(()=>{ig.innerHTML='<div class="instagram-feed-pending"><b>INSTAGRAM LIVE FEED</b><span>API接続後、最新6投稿がここに自動表示されます。</span><a href="https://www.instagram.com/garrawayf_lounge/" target="_blank" rel="noopener">INSTAGRAMを開く ↗</a></div>'});}
 newsSection.dataset.preserve='live-social-news-events';
}