// HERO photography direction: natural people + space + conversation + serendipity.
const heroImg=document.querySelector('.hero-photo img');if(heroImg){heroImg.src='https://drive.google.com/thumbnail?id=1J6Ne_puDhM-7GLyJ1b7n2AMLfLs8ai1u&sz=w2000';heroImg.alt='Garraway Fで人と人が自然につながる風景';heroImg.fetchPriority='high';}
const photo=(id,alt)=>`<figure><img src="https://drive.google.com/thumbnail?id=${id}&sz=w1400" alt="${alt}" loading="lazy"></figure>`;
const statement=document.querySelector('.statement');if(statement){statement.style.display='grid';statement.classList.add('living-photo-story');const old=statement.querySelector('.statement-photo');if(old)old.innerHTML='<img src="https://drive.google.com/thumbnail?id=1Flj3ETVCIChlwQpEvB4BbL19bT3EcQpb&sz=w1800" alt="Garraway Fで自然に生まれる対話" loading="lazy">';}
const facility=document.querySelector('#facility');if(facility&&!facility.querySelector('.living-gallery')){const gallery=document.createElement('div');gallery.className='living-gallery';gallery.innerHTML=`${photo('16bZEROOxM7CvTH3uOLZGiA8TSjNw8Bp3','Garraway Fで集う人たち')}${photo('1fXGYmJIcLKstmGU9TwTfHrdjC3OXh4be','Garraway Fでの対話')}${photo('1Nbri-E3AxcDM-Drofl2_6qf9wRjEqpow','Garraway Fで生まれる活動')}<p class="living-gallery-label">PEOPLE × SPACE / CONVERSATION / ACTION</p>`;facility.querySelector('.facility-grid')?.before(gallery);}
const els=[...document.querySelectorAll('.roles article')];const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:0,transform:'translateY(24px)'},{opacity:1,transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'});io.unobserve(e.target)}}),{threshold:.15});els.forEach(e=>io.observe(e));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const newsSection=document.querySelector('#news');
if(newsSection){
 const head=newsSection.querySelector('.news-live-head');if(head){const kicker=head.querySelector('.kicker');if(kicker)kicker.textContent='LIVE FROM GARRAWAY F';const title=head.querySelector('h2');if(title)title.textContent='今日も、何かが始まっている。';const desc=head.querySelector('p:not(.kicker)');if(desc)desc.textContent='InstagramとXの最新情報から、Garraway Fで生まれている対話・挑戦・出会いをリアルタイムに。';const link=head.querySelector('a');if(link){link.textContent='FOLLOW @GARRAWAYF_LOUNGE ↗';link.href='https://www.instagram.com/garrawayf_lounge/';link.target='_blank';link.rel='noopener';}}
 const frame=newsSection.querySelector('.news-live-frame');if(frame){frame.id='social-preview';frame.className='social-preview live-from-garraway';frame.innerHTML=`<section class="ig-editorial"><div class="ig-editorial-label">LIVE / FUKUOKA / NOW</div><div class="instagram-live-grid" id="instagram-live"><p class="instagram-loading">LOADING LIVE FEED…</p></div><div class="ig-editorial-footer"><b>GARRAWAY F / INSTAGRAM</b><span>THE LIVING LAB IN MOTION</span><a href="https://www.instagram.com/garrawayf_lounge/" target="_blank" rel="noopener">VIEW ALL POSTS ↗</a></div></section><div class="social-side-grid"><article class="social-preview-card facebook"><div class="social-preview-head"><b>FACEBOOK</b><span>EVENTS & BUSINESS NEWS</span></div><div class="fb-page" data-href="https://www.facebook.com/garrawayf/" data-tabs="timeline,events" data-width="500" data-height="520" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false"><blockquote cite="https://www.facebook.com/garrawayf/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/garrawayf/">Garraway F</a></blockquote></div><a class="social-preview-link" href="https://www.facebook.com/garrawayf/" target="_blank" rel="noopener">FACEBOOK ↗</a></article><article class="social-preview-card x x-native"><div class="social-preview-head"><b>X / LATEST</b><span>@GARRAWAY_F · NATIVE FEED</span></div><div class="x-native-feed" id="x-native-feed"><p class="x-loading">LOADING X…</p></div><a class="social-preview-link" href="https://x.com/garraway_f" target="_blank" rel="noopener">最新情報をXで見る ↗</a></article></div>`;}
 if(!document.querySelector('script[src*="connect.facebook.net"]')){const s=document.createElement('script');s.async=true;s.defer=true;s.crossOrigin='anonymous';s.src='https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v22.0';document.body.appendChild(s);}
 const ig=document.querySelector('#instagram-live');if(ig){fetch('data/instagram.json?ts='+Date.now()).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(raw=>{const data=typeof raw.content==='string'?JSON.parse(raw.content):raw;const posts=(data.posts||[]).slice(0,6);if(!posts.length)throw new Error();ig.innerHTML=posts.map((p,i)=>{const d=p.timestamp?new Date(p.timestamp):null;const date=d&&!isNaN(d)?d.toLocaleDateString('ja-JP',{month:'2-digit',day:'2-digit'}).replaceAll('/','.'):'';const reel=p.media_type==='VIDEO'||p.media_type==='REELS'?'<span class="ig-reel">REEL</span>':'';const caption=(p.caption||'').replace(/\s+/g,' ').trim();const excerpt=caption.length>72?caption.slice(0,72)+'…':caption;return `<a class="ig-post ig-post-${i+1}" href="${p.permalink}" target="_blank" rel="noopener"><div class="ig-media"><img src="${p.image}" alt="Garraway F Instagram ${i+1}" loading="lazy">${reel}<span class="ig-number">${String(i+1).padStart(2,'0')}</span></div><div class="ig-copy"><time>${date}</time><p>${esc(excerpt)}</p><span>VIEW POST ↗</span></div></a>`}).join('')}).catch(()=>{ig.innerHTML='<div class="instagram-feed-pending"><b>LIVE FROM GARRAWAY F</b><span>Instagram feed is updating.</span></div>'});}
 const xf=document.querySelector('#x-native-feed');if(xf){fetch('data/x.json?ts='+Date.now()).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{const posts=(data.posts||[]).slice(0,6);if(!posts.length)throw new Error();xf.innerHTML=posts.map((p,i)=>{const d=new Date(p.created_at);const date=!isNaN(d)?d.toLocaleDateString('ja-JP',{month:'2-digit',day:'2-digit'}).replaceAll('/','.'):'LATEST';const image=p.media?.[0]?.url?`<img src="${p.media[0].url}" alt="X post ${i+1}" loading="lazy">`:'';return `<a class="x-post" href="${p.url}" target="_blank" rel="noopener"><div class="x-post-meta"><time>${date}</time><span>${String(i+1).padStart(2,'0')}</span></div>${image}<p>${esc(p.text)}</p><b>VIEW ON X ↗</b></a>`}).join('')}).catch(()=>{xf.innerHTML='<div class="x-feed-pending"><b>X LIVE FEED</b><span>X API接続後、最新投稿がここに自動表示されます。</span></div>'});}
 newsSection.dataset.preserve='live-social-news-events';
}